---
permalink: config-linux/iser-ib-install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Linux Unified Host Utilities, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries, SMcli, SMdevices 
summary: LInstall Linux Unified Host Utilities cuando se usa Iser. 
---
= Instalar y configurar Linux Unified Host Utilities en E-Series (iSER over InfiniBand)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las herramientas de Unified Host Utilities de Linux le ayudan a gestionar el almacenamiento de NetApp, incluidas las políticas de conmutación al nodo de respaldo y las rutas físicas.

.Pasos
. Utilice la https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] Para determinar la versión adecuada de Unified Host Utilities que se debe instalar.
+
Las versiones se enumeran en una columna dentro de cada configuración compatible.

. Descargue las utilidades unificadas de host desde https://mysupport.netapp.com/site/["Soporte de NetApp"^].
+

NOTE: Como alternativa, es posible usar el comando SMcli `-identifyDevices` Para realizar las mismas funciones que la herramienta Unified Host Utility. La interfaz SMcli se incluye en el sistema operativo SANtricity y se puede descargar a través de SANtricity System Manager. Para obtener más información sobre cómo descargar la interfaz SMcli mediante SANtricity System Manager, consulte la https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["Descargue el tema de la CLI en la ayuda en línea de comandos de SANtricity System Manager"^].


