---
permalink: config-linux/nvme-roce-setup-failover-host-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Configure el host para que ejecute la conmutación al nodo de respaldo. 
---
= Configuración de la conmutación por error en el host en E-Series - Linux (NVMe over RoCE)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para proporcionar una ruta redundante a la cabina de almacenamiento, puede configurar el host para que ejecute una conmutación al nodo de respaldo.

.Antes de empezar
Consulta el  https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] para asegurarte de que se instalan todas las actualizaciones necesarias, ya que puede que se requieran correcciones importantes de errores para versiones de SLES o RHEL que no están disponibles en la versión inicial.

.Acerca de esta tarea
Para SLES 15, SLES 16, RHEL 9 y RHEL 10, la multirruta NVMe nativa está habilitada de manera predeterminada y no se requiere ninguna configuración adicional.

.El futuro
Con la función nativa de rutas multivías NVMe activada, link:nvme-roce-access-physical-targets-concept.html["acceder a los volúmenes NVMe de un destino E-Series desde el host"].
