---
permalink: config-linux/nvme-roce-setup-failover-host-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Configure el host para que ejecute la conmutación al nodo de respaldo. 
---
= Configuración de la conmutación por error en el host en E-Series - Linux (NVMe over RoCE)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para proporcionar una ruta redundante a la cabina de almacenamiento, puede configurar el host para que ejecute una conmutación al nodo de respaldo.

.Antes de empezar
Debe instalar los paquetes necesarios en el sistema.

* En el caso de los hosts Red Hat (RHEL), compruebe que los paquetes se han instalado en ejecución `rpm -q device-mapper-multipath`
* En el caso de los hosts SLES, verifique que los paquetes se han instalado ejecutando `rpm -q multipath-tools`



NOTE: Consulte la https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] Para garantizar que se haya instalado cualquier actualización necesaria, ya que es posible que la función multivía no funcione correctamente con las versiones GA de SLES o RHEL.

.Acerca de esta tarea
RHEL 7 y SLES 12 utilizan Device Mapper Multipath (DMMP) para un acceso multivía para NVMe over roce. RHEL 8, RHEL 9 y SLES 15 utilizan una conmutación por error nativa de NVMe integrada. En función del sistema operativo que esté ejecutando, se requiere alguna configuración adicional de multivía para que funcione correctamente.



== Habilite Device Mapper Multipath (DMMP) para RHEL 7 o SLES 12

De manera predeterminada, DM-MP está deshabilitado en RHEL y SLES. Complete los siguientes pasos para activar los componentes DM-MP en el host.

.Pasos
. Añada la entrada del dispositivo NVMe E-Series a la sección Devices de `/etc/multipath.conf` archivo, como se muestra en el siguiente ejemplo:
+
[listing]
----

devices {
        device {
                vendor "NVME"
                product "NetApp E-Series*"
                path_grouping_policy group_by_prio
                failback immediate
                no_path_retry 30
        }
}
----
. Configurar `multipathd` para iniciar al iniciar el sistema.
+
[listing]
----
# systemctl enable multipathd
----
. Comenzar `multipathd` si no se está ejecutando actualmente.
+
[listing]
----
# systemctl start multipathd
----
. Compruebe el estado de `multipathd` para asegurarse de que está activo y en funcionamiento:
+
[listing]
----
# systemctl status multipathd
----




== Configure RHEL 8 con accesos múltiples nativos de NVMe

La función multivía nativa de NVMe está deshabilitada de manera predeterminada en RHEL 8 y debe habilitarse mediante el siguiente procedimiento.

. Configure el  `modprobe` Regla para activar la tecnología multivía nativa del NVMe.
+
[listing]
----
# echo "options nvme_core multipath=y" >> /etc/modprobe.d/50-nvme_core.conf
----
. Repetir `initramfs` con el nuevo `modprobe` parámetro.
+
[listing]
----
# dracut -f
----
. Reinicie el servidor para que esté preparado con la tecnología multivía nativa de NVMe habilitada.
+
[listing]
----
# reboot
----
. Compruebe que la multivía nativa de NVMe esté habilitada después de que el host arranca de nuevo.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
----
+
.. Si el resultado del comando es `N`, A continuación, el acceso multivía nativo de NVMe sigue desactivado.
.. Si el resultado del comando es `Y`, Entonces el acceso multivía nativo de NVMe está activado y cualquier dispositivo NVMe que descubra lo utilizará.





NOTE: Para RHEL 9 y SLES 15, la función multivía nativa de NVMe está habilitada de forma predeterminada y no se requiere ninguna configuración adicional.
