---
permalink: config-linux/nvme-fc-create-filesystems-sles-15-task.html 
sidebar: sidebar 
keywords: file systems, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Para RHEL 8 y SLES 15, crea un sistema de archivos en el dispositivo nvme nativo y monta el sistema de archivos. 
---
= Crear sistemas de archivos (RHEL 8, RHEL 9, SLES 15)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para RHEL 8, RHEL 9 y SLES 15, crea un sistema de archivos en el dispositivo nvme nativo y monta el sistema de archivos.

.Pasos
. Ejecute el comando multipath -ll para obtener una lista de dispositivos nvme.
+
[listing]
----
# multipath -ll
----
+
El resultado de este comando se puede utilizar para buscar los dispositivos asociados `/dev/disk/by-id/nvme-eui.[uuid#]` ubicación. Para el ejemplo siguiente sería `/dev/disc/by-id/nvme-eui.000082dd5c05d39300a0980000a52225`.

+
[listing]
----
eui.000082dd5c05d39300a0980000a52225 [nvme]:nvme0n6 NVMe,NetApp E-Series,08520000
size=4194304 features='n/a' hwhandler='ANA' wp=rw
|-+- policy='n/a' prio=50 status=optimized
| `- 0:0:1 nvme0c0n1 0:0 n/a optimized     live
|-+- policy='n/a' prio=50 status=optimized
| `- 0:1:1 nvme0c1n1 0:0 n/a optimized     live
|-+- policy='n/a' prio=10 status=non-optimized
| `- 0:2:1 nvme0c2n1 0:0 n/a non-optimized live
`-+- policy='n/a' prio=10 status=non-optimized
  `- 0:3:1 nvme0c3n1 0:0 n/a non-optimized live
----
. Cree un sistema de archivos en la partición para el dispositivo nvme deseado mediante la ubicación `/dev/disk/by-id/nvme-eui.[id#]`.
+
El método para crear un sistema de archivos varía en función del sistema de archivos elegido. En este ejemplo se muestra la creación de un sistema de archivos ext4.

+
[listing]
----
# mkfs.ext4 /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225
mke2fs 1.42.11 (22-Oct-2019)
Creating filesystem with 2620928 4k blocks and 655360 inodes
Filesystem UUID: 97f987e9-47b8-47f7-b434-bf3ebbe826d0
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done
----
. Cree una carpeta para montar el nuevo dispositivo.
+
[listing]
----
# mkdir /mnt/ext4
----
. Monte el dispositivo.
+
[listing]
----
# mount /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225 /mnt/ext4
----

