---
permalink: config-linux/nvme-roce-discover-connect-storage-host-task.html 
sidebar: sidebar 
keywords: discover storage, host, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Antes de realizar definiciones de cada host en SANtricity System Manager, es necesario detectar los puertos de la controladora de destino del host y, a continuación, establecer conexiones NVMe. 
---
= Detectar y conectarse al almacenamiento desde el host en E-Series - Linux (NVMe over RoCE)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de realizar definiciones de cada host en SANtricity System Manager, es necesario detectar los puertos de la controladora de destino del host y, a continuación, establecer conexiones NVMe.

.Pasos
. Comprueba que puedes hacer ping desde el host a cada puerto HIC de la matriz utilizando la tasa de MTU prevista mediante el siguiente comando:
+
[listing]
----
ping -M do -s <size> <IP of array HIC port>
----
. Detecte subsistemas disponibles en el destino NVMe-of para todas las rutas usando el siguiente comando:
+
[listing]
----
nvme discover -t rdma -a target_ip_address
----
+
En este comando, `target_ip_address` Es la dirección IP del puerto de destino.

+

NOTE: La `nvme discover` el comando detecta todos los puertos de la controladora en el subsistema, independientemente del acceso al host.

+
[listing]
----
# nvme discover -t rdma -a 192.168.1.77
Discovery Log Number of Records 2, Generation counter 0
=====Discovery Log Entry 0======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  0
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:5700.600a098000a527a7000000005ab3af94
traddr:  192.168.1.77
rdma_prtype: roce
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 1======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:5700.600a098000a527a7000000005ab3af94
traddr:  192.168.2.77
rdma_prtype: roce
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
----
. Repite el paso 2 para cualquier otra conexión.
. Conéctese al subsistema detectado en la primera ruta con el comando: `nvme connect -t rdma -n discovered_sub_nqn -a target_ip_address -Q queue_depth_setting -l controller_loss_timeout_period`
+

NOTE: El comando indicado anteriormente no se mantiene tras el reinicio. El comando  `nvme connect` deberá ejecutarse después de cada reinicio para restablecer las conexiones NVMe.

+

NOTE: No se establecen conexiones para ningún puerto detectado al que el host no puede acceder.

+

NOTE: Si especifica un número de puerto con este comando, la conexión genera un error. El puerto predeterminado es el único puerto configurado para las conexiones.

+

NOTE: El valor recomendado para la profundidad de la cola es 1024. Sustituye el valor predeterminado de 128 por 1024 usando la opción de línea de comandos `-Q 1024`, como se muestra en el siguiente ejemplo.

+

NOTE: El tiempo de espera de pérdida de la controladora recomendado en segundos es de 60 minutos (3600 segundos). Anule el ajuste predeterminado de 600 segundos con 3600 segundos mediante el `-l 3600` opción de línea de comandos, como se muestra en el siguiente ejemplo.

+
[listing]
----
# nvme connect -t rdma -a 192.168.1.77 -n nqn.1992-
08.com.netapp:EF80.600a098000a527a7000000005ab3af94 -Q 1024 -l 3600
----
. Repite el paso 4 para conectar el subsistema detectado en la segunda ruta.
. **Opcional** - configura tu host para que detecte automáticamente los destinos y se conecte a ellos en cada arranque.
+
.. Agrega los parámetros de descubrimiento de los pasos 2 y 3 a `/etc/nvme/discovery.conf` usando el siguiente procedimiento y formato:
+
[listing]
----
# echo "--transport=rdma --traddr= target_ip_address --trsvcid=4420" | sudo tee -a /etc/nvme/discovery.conf
----
.. Activa el servicio nvmf-autoconnect después de rellenar el archivo  `/etc/nvme/discovery.conf` usando el siguiente comando:
+
[listing]
----
sudo systemctl enable nvmf-autoconnect.service
----




.El futuro
Una vez que hayas establecido las conexiones, link:nvme-roce-define-host-task.html["define el host"].
