---
permalink: config-linux/nvme-roce-setup-host-side-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: La configuración del iniciador NVMe en un entorno roce incluye la instalación y la configuración de los paquetes rdma-Core y nvme-cli, la configuración de direcciones IP del iniciador y la configuración de la capa NVMe-of en el host. 
---
= Configure el iniciador de NVMe a través de RoCE en el host en E-Series - Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuración del iniciador NVMe en un entorno roce incluye la instalación y la configuración de los paquetes rdma-Core y nvme-cli, la configuración de direcciones IP del iniciador y la configuración de la capa NVMe-of en el host.

.Antes de empezar
Debes estar utilizando la última versión compatible del sistema operativo RHEL 9, RHEL 10, SLES 15 o SLES 16 con service pack. Consulta https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] para ver una lista completa de los requisitos más recientes.

.Pasos
. Instale los paquetes rdma y nvme-cli:
+
*SLES 15 o SLES 16*

+
[listing]
----

# zypper install rdma-core
# zypper install nvme-cli
----
+
*RHEL 9 y RHEL 10*

+
[listing]
----

# yum install rdma-core
# yum install nvme-cli
----



NOTE: Si utilizas un HCA de NVIDIA y deseas usar el controlador externo DOCA, consulta la link:https://developer.nvidia.com/doca-downloads["Documentación de NVIDIA DOCA"] para obtener información sobre cómo instalarlo correctamente en este entorno.

. Para RHEL 9, instala los scripts de red:
+
* RHEL 9*

+
[listing]
----
# yum install NetworkManager-initscripts-updown
----
+

NOTE: Los scripts de red no están disponibles para RHEL 10.

. Obtenga el host NQN, que se usarán para configurar el host en una cabina de.
+
[listing]
----
# cat /etc/nvme/hostnqn
----
. Configure direcciones IP IPv4 en los puertos ethernet que se utilizan para conectar NVMe over roce. Para cada interfaz de red, cree un script de configuración que contenga las diferentes variables para esa interfaz.
+
Las variables utilizadas en este paso se basan en el hardware del servidor y el entorno de red. Las variables incluyen la `IPADDR` y.. `GATEWAY`. Estas son instrucciones de ejemplo para SLES y RHEL:

+
*SLES 15*

+
Crea el archivo de ejemplo  `/etc/sysconfig/network/ifcfg-eth4` con el siguiente contenido, donde MTU se establece en el valor más alto que se puede alcanzar sin fragmentación de paquetes (normalmente 9000).

+
[listing]
----
BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='192.168.1.87/24'
GATEWAY='192.168.1.1'
MTU=9000
NAME='MT27800 Family [ConnectX-5]'
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
A continuación, cree el archivo de ejemplo `/etc/sysconfig/network/ifcfg-eth5`:

+
[listing]
----
BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='192.168.2.87/24'
GATEWAY='192.168.2.1'
MTU=9000
NAME='MT27800 Family [ConnectX-5]'
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
*RHEL 9, RHEL 10 o SLES 16*

+
Utilice la `nmtui` herramienta para activar y editar una conexión. A continuación se muestra un archivo de ejemplo `/etc/NetworkManager/system-connections/eth4.nmconnection` la herramienta generará:

+
[listing]
----

[connection]
id=eth4
uuid=<unique uuid>
type=ethernet
interface-name=eth4

[ethernet]
mtu=9000

[ipv4]
address1=192.168.1.87/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
+
A continuación se muestra un archivo de ejemplo `/etc/NetworkManager/system-connections/eth5.nmconnection` la herramienta generará:

+
[listing]
----

[connection]
id=eth5
uuid=<unique uuid>
type=ethernet
interface-name=eth5

[ethernet]
mtu=9000

[ipv4]
address1=192.168.2.87/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
. Habilite las interfaces de red:
+
[listing]
----

# nmcli connection up eth4
# nmcli connection up eth5
----
. Configure la capa NVMe-of en el host. Cree el siguiente archivo en `/etc/modules-load.d/` para cargar el `nvme_rdma` el módulo del kernel y asegúrese de que el módulo del kernel estará siempre encendido, incluso después de un reinicio:
+
[listing]
----

# cat /etc/modules-load.d/nvme_rdma.conf
  nvme_rdma
----
. Reinicie el host.
+
.. También puedes cargar el `nvme_rdma` kernel sin reiniciar ejecutando este comando:
+
[listing]
----

# modeprobe nvme_rdma
----


. Verifica que el módulo del kernel  `nvme_rdma` esté cargado, ejecuta este comando:
+
[listing]
----
# lsmod | grep nvme
nvme_rdma              36864  0
nvme_fabrics           24576  1 nvme_rdma
nvme_core             114688  5 nvme_rdma,nvme_fabrics
rdma_cm               114688  7 rpcrdma,ib_srpt,ib_srp,nvme_rdma,ib_iser,ib_isert,rdma_ucm
ib_core               393216  15 rdma_cm,ib_ipoib,rpcrdma,ib_srpt,ib_srp,nvme_rdma,iw_cm,ib_iser,ib_umad,ib_isert,rdma_ucm,ib_uverbs,mlx5_ib,qedr,ib_cm
t10_pi                 16384  2 sd_mod,nvme_core
----
+
.El futuro
Después de que configures el iniciador NVMe sobre RoCE en el host, link:nvme-roce-configure-storage-connections-task.html["configurar los ajustes del puerto NVMe sobre RoCE"].


