---
permalink: config-linux/nvme-fc-setup-host-side-task.html 
sidebar: sidebar 
keywords: NVMe over Fibre Channel, host side, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: La configuración del iniciador de NVMe en un entorno Fibre Channel incluye la instalación y la configuración del paquete nvme-cli, y habilitar el iniciador de NVMe/FC en el host. 
---
= Configure NVMe over Fibre Channel en el lado del host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuración del iniciador de NVMe en un entorno Fibre Channel incluye la instalación y la configuración del paquete nvme-cli y para habilitar el iniciador de NVMe/FC en el host.

.Acerca de esta tarea
El siguiente procedimiento es para RHEL 7, RHEL 8, RHEL 9, SLES 12 y SLES 15 mediante dispositivos HBA FC compatibles con Broadcom Emulex o QLogic NVMe/FC. Para obtener más información sobre las versiones de estos sistemas operativos o HBA, consulte https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^].

.Pasos
. Instale el `nvme-cli` paquete:
+
*SLES 12 o SLES 15*

+
[listing]
----

# zypper install nvme-cli
----
+
* RHEL 7, RHEL 8 O RHEL 9*

+
[listing]
----

# yum install nvme-cli
----
+
.. Solo para RHEL 7, descargue e instale un script de conexión automática de Broadcom externo para conexiones NVMe/FC a través de la https://www.broadcom.com/support/download-search["Sitio web de Broadcom"^]. Introduzca la palabra clave *Autoconnect Script File for Inbox NVMe over FC Drivers* y elija la última versión específica de su sistema operativo.
.. Para Qlogic, modificar `/lib/systemd/system/nvmefc-boot-connections.service` Después de instalar el script de conexión automática NVMe/FC de Broadcom para contener las siguientes acciones:
+
[listing]
----
[Unit]
Description=Auto-connect to subsystems on FC-NVME devices found during boot

[Service]
Type=oneshot
ExecStart=/bin/sh -c "echo add > /sys/class/fc/fc_udev_device/nvme_discovery"

[Install]
WantedBy=default.target
----


. Active e inicie `nvmefc-boot-connections` servicio.
+
[listing]
----
systemctl enable nvmefc-boot-connections.service
----
+
[listing]
----
systemctl start nvmefc-boot-connections.service
----


*Configuración del host para los HBA Emulex:*


NOTE: Los siguientes pasos solo son para los HBA de Emulex.

. Configurado `lpfc_enable_fc4_type` para `3` Para habilitar SLES12 SP4 como iniciador NVMe/FC.
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_enable_fc4_type=3
----
. Vuelva a crear el `initrd` Para obtener el cambio de Emulex y el cambio de los parámetros de arranque.
+
[listing]
----
# dracut --force
----
. Reinicie el host para cargar los cambios en el `Ipfc` controlador.
+
[listing]
----
# reboot
----
+
El host se reinicia y el iniciador de NVMe/FC está habilitado en el host.

+

NOTE: Después de completar la configuración en el lado del host, la conexión de los puertos NVMe over Fibre Channel se produce automáticamente.


