---
permalink: config-linux/nvme-fc-setup-failover-host-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Configure el host para que ejecute la conmutación al nodo de respaldo. 
---
= Configuración de la conmutación por error en el host en E-Series - Linux (NVMe over FC)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para proporcionar una ruta redundante a la cabina de almacenamiento, puede configurar el host para que ejecute una conmutación al nodo de respaldo.

.Antes de empezar
Debe instalar los paquetes necesarios en el sistema.

* En el caso de los hosts Red Hat (RHEL), compruebe que los paquetes se han instalado en ejecución `rpm -q device-mapper-multipath`
* En el caso de los hosts SLES, verifique que los paquetes se han instalado ejecutando `rpm -q multipath-tools`


 SLES 12 use Device Mapper Multipath (DMMP) for multipathing when using NVMe over Fibre Channel. RHEL 8, RHEL 9, and SLES 15 use a built-in Native NVMe Failover. Depending on which OS you are running, some additional configuration of multipath is required to get it running properly.


== Activar Device Mapper Multivía (DMMP) para SLES 12

Por defecto, DM-MP está desactivado en SLES. Complete los siguientes pasos para habilitar los componentes DM-MP en el host.

.Pasos
. Añada la entrada del dispositivo NVMe E-Series a la sección dispositivos del archivo /etc/multipath.conf, como se muestra en el siguiente ejemplo:
+
[listing]
----

devices {
        device {
                vendor "NVME"
                product "NetApp E-Series*"
                path_grouping_policy group_by_prio
                failback immediate
                no_path_retry 30
        }
}
----
. Configurar `multipathd` para iniciar al iniciar el sistema.
+
[listing]
----
# systemctl enable multipathd
----
. Comenzar `multipathd` si no se está ejecutando actualmente.
+
[listing]
----
# systemctl start multipathd
----
. Compruebe el estado de `multipathd` para asegurarse de que está activo y en funcionamiento:
+
[listing]
----
# systemctl status multipathd
----




== Configure el protocolo multivía nativo de NVMe para RHEL 8

.Acerca de esta tarea
La función multivía nativa de NVMe está deshabilitada de manera predeterminada en RHEL 8 y debe habilitarse mediante los pasos siguientes.

.Pasos
. Configuración `modprobe` Regla para activar la tecnología multivía nativa del NVMe.
+
[listing]
----
# echo "options nvme_core multipath=y" >> /etc/modprobe.d/50-nvme_core.conf
----
. Repetir `initramfs` con el nuevo parámetro modprobe.
+
[listing]
----
# dracut -f
----
. Reinicie el servidor para que esté disponible con el sistema multivía nativo de NVMe habilitado
+
[listing]
----
# reboot
----
. Compruebe que se haya habilitado el acceso multivía nativo de NVMe después de que el host arranca de nuevo.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
----
+
.. Si el resultado del comando es `N`, A continuación, el acceso multivía nativo de NVMe sigue desactivado.
.. Si el resultado del comando es `Y`, Entonces el acceso multivía nativo de NVMe está activado y cualquier dispositivo NVMe que descubra lo utilizará.





NOTE: Para RHEL 9 y SLES 15, la función multivía nativa de NVMe está habilitada de forma predeterminada y no se requiere ninguna configuración adicional.
