---
permalink: config-linux/nvme-tcp-setup-host-side-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: La configuración del iniciador NVMe en un entorno TCP incluye instalar y configurar el paquete nvme-cli, configurar las direcciones IP del iniciador y configurar la capa NVMe-oF en el host. 
---
= Configura el iniciador de NVMe sobre TCP en un host Linux E-Series
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuración del iniciador NVMe en un entorno TCP incluye instalar y configurar el paquete nvme-cli, configurar las direcciones IP del iniciador y configurar la capa NVMe-oF en el host.

.Antes de empezar
Debes estar utilizando la última versión compatible del sistema operativo RHEL 9, RHEL 10, SLES 15 o SLES 16 con service pack. Consulta https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] para ver una lista completa de los requisitos más recientes.

.Pasos
. Si estás utilizando el controlador ethernet inbox para tu HCA, instala el paquete  `nvme-cli` de la siguiente manera:
+
*SLES 15 o SLES 16*

+
[listing]
----

# zypper install nvme-cli
----
+
*RHEL 9 y RHEL 10*

+
[listing]
----

# yum install nvme-cli
----
+
Si utilizas un HCA de NVIDIA y deseas usar el controlador DOCA externo, consulta la link:https://developer.nvidia.com/doca-downloads["Documentación de NVIDIA"] para obtener información sobre cómo instalarlo correctamente en este entorno.

. Para RHEL 9, instala los scripts de red:
+
* RHEL 9*

+
[listing]
----
# yum install NetworkManager-initscripts-updown
----
+

NOTE: Los scripts de red no están disponibles para RHEL 10.

. Obtenga el host NQN, que se usarán para configurar el host en una cabina de.
+
[listing]
----
# cat /etc/nvme/hostnqn
----
. Configura las direcciones IP IPv4 en los puertos ethernet utilizados para conectar NVMe sobre TCP. Para cada interfaz de red, crea un script de configuración que contenga las diferentes variables de esa interfaz.
+
Las variables utilizadas en este paso se basan en el hardware del servidor y el entorno de red. Las variables incluyen la `IPADDR` y.. `GATEWAY`. Estas son instrucciones de ejemplo para SLES y RHEL:

+
*SLES 15*

+
Crea el archivo de ejemplo  `/etc/sysconfig/network/ifcfg-eth4` con el siguiente contenido.

+
[listing]
----
BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='192.168.1.87/24'
GATEWAY='192.168.1.1'
MTU=9000
NAME='<adapter name>'
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
A continuación, cree el archivo de ejemplo `/etc/sysconfig/network/ifcfg-eth5`:

+
[listing]
----
BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='192.168.2.87/24'
GATEWAY='192.168.2.1'
MTU=9000
NAME='<adapter name>'
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
*RHEL 9, RHEL 10 o SLES 16*

+
Utilice la `nmtui` herramienta para activar y editar una conexión. A continuación se muestra un archivo de ejemplo `/etc/NetworkManager/system-connections/eth4.nmconnection` la herramienta generará:

+
[listing]
----

[connection]
id=eth4
uuid=<unique uuid>
type=ethernet
interface-name=eth4

[ethernet]
mtu=9000

[ipv4]
address1=192.168.1.87/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
+
A continuación se muestra un archivo de ejemplo `/etc/NetworkManager/system-connections/eth5.nmconnection` la herramienta generará:

+
[listing]
----

[connection]
id=eth5
uuid=<unique uuid>
type=ethernet
interface-name=eth5

[ethernet]
mtu=9000

[ipv4]
address1=192.168.2.87/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
. Habilite las interfaces de red:
+
[listing]
----

# nmcli connection up eth4
# nmcli connection up eth5
----
. Configura la capa NVMe-oF en el host. Crea el siguiente archivo en  `/etc/modules-load.d/` para cargar el módulo de kernel  `nvme_tcp` y asegurarte de que el módulo de kernel siempre esté activo, incluso después de un reinicio:
+
[listing]
----

# cat /etc/modules-load.d/nvme_tcp.conf
  nvme_tcp
----
. Reinicie el host.
+
.. Como alternativa, puedes cargar el módulo del kernel  `nvme_tcp` sin reiniciar ejecutando este comando:
+
[listing]
----

# modprobe nvme_tcp
----


. Verifica que el módulo del kernel  `nvme_tcp` esté cargado, ejecuta este comando:
+
[listing]
----
# lsmod | grep nvme
nvme_tcp               45056  0
nvme_fabrics           24576  1 nvme_tcp
nvme_core             114688  5 nvme_tcp,nvme_fabrics
t10_pi                 16384  2 sd_mod,nvme_core
----
+
.El futuro
Una vez que hayas configurado el iniciador de NVMe sobre TCP en el host, link:nvme-tcp-configure-storage-connections-task.html["Configura los ajustes del puerto NVMe sobre TCP"].


