---
permalink: config-linux/nvme-tcp-configure-storage-connections-task.html 
sidebar: sidebar 
keywords: NVMe over TCP, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Si tu controlador dispone de una conexión para NVMe sobre TCP, puedes configurar los ajustes del puerto NVMe desde la página Hardware o la página Sistema en SANtricity System Manager. 
---
= Configura las conexiones NVMe sobre TCP del almacenamiento E-Series para hosts Linux
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tu controlador dispone de una conexión para NVMe sobre TCP, puedes configurar los ajustes del puerto NVMe desde la página Hardware o la página Sistema en SANtricity System Manager.

.Antes de empezar
Asegúrese de tener lo siguiente:

* Un puerto de host NVMe sobre TCP en tu controlador; de lo contrario, la configuración de NVMe sobre TCP no está disponible en System Manager.
* La dirección IP de la conexión de host.


.Acerca de esta tarea
Puedes acceder a la configuración de NVMe sobre TCP desde la página *Hardware* o desde el menú:settings[sistema]. Esta tarea describe cómo configurar los puertos desde la página Hardware.


NOTE: Los ajustes y funciones de NVMe sobre TCP solo aparecen si el controlador de tu matriz de almacenamiento incluye un puerto NVMe sobre TCP.

.Pasos
. En el panel izquierdo de la interfaz de System Manager, selecciona *Hardware*.
. Haz clic en el controlador con el puerto NVMe sobre TCP que quieras configurar.
+
Aparece el menú contextual de la controladora.

. Selecciona *Configurar NVMe over TCP ports*.
+
Se abre el cuadro de diálogo *Configurar NVMe sobre puertos TCP*.

. En la lista desplegable, seleccione el puerto que desea configurar y, a continuación, haga clic en *Siguiente*.
. Seleccione la configuración de puertos que desea utilizar y, a continuación, haga clic en *Siguiente*.
+
Para ver todas las configuraciones de puerto, haga clic en el enlace *Mostrar más opciones de puerto* situado a la derecha del cuadro de diálogo.

+
|===
| Opción de configuración de puertos | Descripción 


 a| 
Velocidad de puerto ethernet configurada
 a| 
Selecciona la velocidad deseada. Las opciones que aparecen en la lista desplegable dependen de la velocidad máxima que puede admitir tu red (por ejemplo, 10 Gbps). Los valores posibles incluyen:

** Autonegociar
** 10 Gbps
** 25 Gbps
** 40 Gbps
** 50 Gbps
** 100 Gbps
** 200 Gbps



NOTE: La velocidad del puerto NVMe sobre TCP configurada debe coincidir con la capacidad de velocidad del SFP en el puerto seleccionado.



 a| 
Modo de corrección de errores hacia adelante (FEC) configurado
 a| 
Selecciona el modo FEC deseado. Las opciones que aparecen en la lista desplegable dependen de la velocidad seleccionada actualmente y solo muestran las opciones compatibles con esa velocidad. No todos los modos FEC están disponibles para todas las velocidades. Los valores posibles incluyen:

** Ninguno
** Reed-Solomon
** Normativa contra incendios
** Automático




 a| 
Habilite IPv4 o habilite IPv6
 a| 
Seleccione una o ambas opciones para habilitar la compatibilidad con las redes IPv4 e IPv6.



 a| 
Tamaño de MTU (disponible haciendo clic en *Mostrar más opciones de puerto*).
 a| 
De ser necesario, introduzca un nuevo tamaño en bytes para la unidad de transmisión máxima (MTU). El tamaño de MTU predeterminado es de 1500 bytes por trama. Debe introducir un valor entre 1500 y 9000.

|===
+
Si seleccionó *Activar IPv4*, se abre un cuadro de diálogo para seleccionar la configuración IPv4 después de hacer clic en *Siguiente*. Si seleccionó *Activar IPv6*, se abre un cuadro de diálogo para seleccionar la configuración de IPv6 después de hacer clic en *Siguiente*. Si seleccionó ambas opciones, primero se abre el cuadro de diálogo de configuración IPv4 y después de hacer clic en *Siguiente*, se abre el cuadro de diálogo de configuración de IPv6.

. Configure los valores para IPv4 o IPv6 de forma automática o manual. Para ver todas las opciones de configuración de puertos, haga clic en el enlace *Mostrar más valores* situado a la derecha del cuadro de diálogo.
+
|===
| Opción de configuración de puertos | Descripción 


 a| 
Obtener automáticamente la configuración del servidor DHCP
 a| 
Seleccione esta opción para obtener automáticamente la configuración.



 a| 
Especificar manualmente la configuración estática
 a| 
Seleccione esta opción e introduzca una dirección estática en los campos. En el caso de IPv4, incluya la máscara de subred y la puerta de enlace. En el caso de IPv6, incluya las direcciones IP enrutable y la dirección IP del enrutador.


NOTE: Si solo hay una dirección IP enrutable, defina la dirección restante como 0:0:0:0:0:0:0:0.



 a| 
Active la compatibilidad con VLAN (disponible haciendo clic en *Mostrar más opciones*).
 a| 

NOTE: Esta opción solo está disponible en un entorno iSCSI. No está disponible en un entorno NVMe sobre TCP.



 a| 
Activar prioridad ethernet (disponible haciendo clic en *Mostrar más valores*).
 a| 

NOTE: Esta opción solo está disponible en un entorno iSCSI. No está disponible en un entorno NVMe sobre TCP.

|===
. Haga clic en *Finalizar*.


.El futuro
Una vez que hayas configurado los ajustes del puerto NVMe sobre TCP, link:nvme-tcp-discover-connect-storage-host-task.html["detectar y conectar el almacenamiento en el host"].
