---
permalink: config-linux/nvme-roce-create-filesystems-sles-15-task.html 
sidebar: sidebar 
keywords: file systems, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Para RHEL 9, RHEL 10, SLES 15 y SLES 16, creas un sistema de archivos en el dispositivo NVMe nativo y montas el sistema de archivos. 
---
= Crear sistemas de archivos en E-Series - Linux (NVMe sobre RoCE)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para RHEL 9, RHEL 10, SLES 15 y SLES 16, creas un sistema de archivos en el dispositivo NVMe nativo y montas el sistema de archivos.

.Antes de empezar
Asegúrate de haber completado la tarea link:nvme-roce-access-physical-targets-concept.html["acceder a volúmenes NVMe de un destino E-Series desde el host"] para garantizar que los dispositivos NVMe estén correctamente configurados y sean accesibles.

.Pasos
. Cree un sistema de archivos en la partición para el dispositivo nvme deseado mediante la ubicación `/dev/disk/by-id/nvme-eui.[id#]`.
+
El método para crear un sistema de archivos varía en función del sistema de archivos elegido. Este ejemplo muestra cómo crear un `ext4` sistema de archivos.

+
[listing]
----
# mkfs.ext4 /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225
mke2fs 1.42.11 (22-Oct-2019)
Creating filesystem with 2620928 4k blocks and 655360 inodes
Filesystem UUID: 97f987e9-47b8-47f7-b434-bf3ebbe826d0
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done
----
. Cree una carpeta para montar el nuevo dispositivo.
+
[listing]
----
# mkdir /mnt/ext4
----
. Monte el dispositivo.
+
[listing]
----
# mount /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225 /mnt/ext4
----


.El futuro
Una vez creados los sistemas de archivos, link:nvme-roce-worksheet-for-concept.html["Guarda la información de configuración de tu NVMe over RoCE"].
