---
permalink: config-linux/nvme-roce-verify-linux-config-support-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Para garantizar una operación fiable, debe crear un plan de implementación y, a continuación, utilizar la herramienta de matriz de interoperabilidad (IMT) de NetApp para verificar que se admite toda la configuración.' 
---
= Verificar la compatibilidad con Linux y las restricciones de revisión
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como primer paso, debe verificar que su configuración de Linux sea compatible y revisar también las restricciones de controladora, switch, host y recuperación.



== Compruebe que la configuración de Linux sea compatible

Para garantizar una operación fiable, debe crear un plan de implementación y, a continuación, utilizar la herramienta de matriz de interoperabilidad (IMT) de NetApp para verificar que se admite toda la configuración.

.Pasos
. Vaya a la https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^].
. Haga clic en el icono *Búsqueda de soluciones*.
. En el área de menú:Protocolos[Host SAN], haga clic en el botón *Agregar* situado junto a *Host SAN E-Series*.
. Haga clic en *Ver criterios de búsqueda de afinado*.
+
Se muestra la sección criterios de búsqueda de afinado. En esta sección, puede seleccionar el protocolo aplicable, así como otros criterios para la configuración como sistema operativo, sistema operativo de NetApp y controlador multivía de host.

. Seleccione los criterios que sabe que desea utilizar para su configuración y, a continuación, vea los elementos de configuración compatibles que se aplican.
. Según sea necesario, realice las actualizaciones para el sistema operativo y el protocolo que se prescriben en la herramienta.
+
Puede acceder a la información detallada de la configuración elegida en la página Ver configuraciones admitidas haciendo clic en la flecha de la página derecha.





== Verificar las restricciones de NVMe over roce

Antes de usar NVMe over roce, consulte https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] para revisar las últimas restricciones de controladora, host y recuperación.



=== Restricciones de conmutación


CAUTION: *RIESGO DE PÉRDIDA DE DATOS.* debe habilitar el control de flujo para su uso con Global Pause Control en el switch para eliminar el riesgo de pérdida de datos en un entorno NVMe over roce.



=== Restricciones de almacenamiento y recuperación ante desastres

* No se admiten el mirroring asíncrono y síncrono.
* No se admite thin provisioning (la creación de volúmenes finos).

