---
sidebar: sidebar 
permalink: manage-storage.html 
keywords: online help, System Manager, Unified Manager 
summary: Gestionar el almacenamiento 
---
= Gestionar el almacenamiento
:allow-uri-read: 


[role="lead"]
Use los siguientes enlaces para acceder a documentación que describe cómo configurar, gestionar y supervisar objetos de almacenamiento y sistemas de almacenamiento E-Series. Los vínculos lo llevan a otro sitio de documentación.



== Ayuda en línea para System Manager 11.7

Acceda a https://docs.netapp.com/us-en/e-series-santricity/system-manager/index.html["Ayuda en línea de SANtricity System Manager 11.7"^], donde puede encontrar información acerca de cómo planificar, configurar, administrar y solucionar problemas en la matriz de almacenamiento.



== Ayuda en línea para Unified Manager 5

Acceda a https://docs.netapp.com/us-en/e-series-santricity/unified-manager/index.html["Ayuda en línea de SANtricity Unified Manager 5"^], donde puede aprender a ejecutar comandos de administración de almacenamiento en varias matrices de almacenamiento en red.



== Referencia de comandos

Acceda a https://docs.netapp.com/us-en/e-series-cli/index.html["Referencia de comandos"^], Donde puede aprender a configurar y supervisar las matrices de almacenamiento mediante comandos de la interfaz de línea de comandos (CLI).
