---
sidebar: sidebar 
permalink: rackmount-hardware.html 
keywords: rackmount, rack-mount, install in rack, rails 
summary: El hardware de montaje en bastidor se usa para instalar tu hardware en un bastidor o gabinete. Las instrucciones de instalación deberían estar incluidas en la caja del hardware de montaje en bastidor. Sin embargo, si necesitas acceder a las instrucciones de instalación, usa el enlace correspondiente de abajo. 
---
= Hardware de montaje en bastidor - E-Series
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
El hardware de montaje en bastidor se utiliza para instalar tu sistema de almacenamiento en un bastidor o armario. Las instrucciones de instalación deberían estar incluidas en la caja del hardware de montaje en bastidor. Sin embargo, si necesitas acceder a las instrucciones de instalación, usa el enlace correspondiente de abajo.

Para los sistemas de almacenamiento más recientes, puedes verificar el hardware de montaje en bastidor compatible consultando NetApp Hardware Universe en https://hwu.netapp.com["Hardware Universe de NetApp"^].



== Rieles de soporte ajustables

Acceso https://mysupport.netapp.com/ecm/ecm_download_file/ECMP1652045["Instalación de rieles de soporte ajustables"^] para la instalación de un soporte de controladora-unidad o un soporte de unidades que se envió por separado (no instalado ya en el armario). Este procedimiento se aplica a las siguientes bandejas 2U (9 cm o 3.5 pulgadas):

* DE1600 o DE5600
* E2612 o E2624
* E5412, E5424, E5512 O E5524




== Rack de dos puestos - 2U

Acceso https://mysupport.netapp.com/ecm/ecm_download_file/ECMM1280302["Instalación del equipo de 2U en un rack de dos postes"^].



== Rack o armario de cuatro postes -- 2U

Acceso https://mysupport.netapp.com/ecm/ecm_download_file/ECMLP2484194["Instalación de un compartimento 2U de 12 unidades en un rack o armario de cuatro parantes"^].



== Rack de cuatro postes -- SuperRail

Accede a https://docs.netapp.com/us-en/ontap-systems/platform-supplemental/superrail-install.html["Instala SuperRail en una estantería de cuatro postes"^].
