---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: Nuevas funciones del sistema operativo SANtricity. 
---
= Novedades en SANtricity OS
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En la siguiente tabla, se describen las nuevas funciones del sistema operativo SANtricity 11,8 para la gestión integrada de las controladoras EF300, EF600, E2800/EF280 y E5700/EF570.



== Nuevas funciones en la versión 11,80

[cols="35h,~"]
|===
| Nueva función | Descripción 


 a| 
Exploración de paridad de volumen mejorada
 a| 
El análisis de paridad de volúmenes ahora se puede iniciar como proceso en segundo plano mediante la API DE REST o la interfaz de línea de comandos. El análisis de paridad resultante se ejecutará en segundo plano siempre que sea necesario para completar la operación de análisis. Las operaciones de análisis sobrevivirán a los reinicios de la controladora y las operaciones de conmutación por error.



 a| 
Compatibilidad con SAML para Unified Manager
 a| 
Unified Manager ahora es compatible con SAML (lenguaje de marcado de aserción de seguridad). Una vez que SAML se habilita para Unified Manager, los usuarios deben usar la autenticación multifactor con el proveedor de identidades para poder interactuar con la interfaz de usuario. Tenga en cuenta que una vez que se habilita SAML en Unified Manager, la API DE REST no se puede usar sin pasar por el IdP para autenticar las solicitudes.



 a| 
Función de configuración automática
 a| 
Ahora admite la capacidad de establecer el parámetro de tamaño de bloque de volumen que se utilizará con la función Auto Configuration para la configuración inicial de la cabina. Esta función solo está disponible en la CLI como parámetro «blocksize».



 a| 
Firma criptográfica del firmware de la controladora
 a| 
El firmware de la controladora está firmado criptográficamente. Las firmas se comprueban durante la descarga inicial y en cada arranque de la controladora. No se espera ningún impacto sobre el usuario final. Las firmas están respaldadas por un certificado de validación extendida emitido por la CA.



 a| 
Firma criptográfica del firmware de la unidad
 a| 
El firmware de la unidad está firmado criptográficamente. Las firmas se comprueban durante la descarga inicial y están respaldadas por un certificado de validación extendida emitido por la CA. El contenido del firmware de la unidad ahora se entrega como archivo ZIP, que contiene el firmware no firmado más antiguo, así como el firmware nuevo firmado. El usuario debe seleccionar el archivo adecuado en función de la versión de lanzamiento del código que se esté ejecutando en el sistema de destino.



 a| 
Gestión de servidores de claves externos: Tamaño de clave de certificado
 a| 
El nuevo tamaño de clave de certificado predeterminado es de 3072 bits (desde 2048). Se admiten tamaños de llave de hasta 4096 bits. Debe cambiarse un bit de NVSRAM para que admita los tamaños de claves no predeterminados.

Los valores de selección de tamaño de clave son los siguientes:

* EL VALOR PREDETERMINADO ES DE 15 0
* LONGITUD 2048 = 1
* LONGITUD 3072 = 2
* LONGITUD 4096 = 3


Para cambiar el tamaño de clave a 4096 mediante SMcli:

`set controller[b] globalnvsrambyte[0xc0]=3;`
`set controller[a] globalnvsrambyte[0xc0]=3;`

Interrogue el tamaño de la clave:

`show allcontrollers globalnvsrambyte[0xc0];`



 a| 
Mejoras del pool de discos
 a| 
Los pools de discos creados con controladoras que ejecutan 11,80 o superior serán pools _Version 1_ en vez de pools _Version 0_. La operación de degradación está restringida cuando existe un pool de discos _Versión 1_.

La versión de un pool de discos se puede identificar en el perfil de la cabina de almacenamiento.



 a| 
System Manager y Unified Manager no se iniciarán a menos que se cumplan los requisitos mínimos del explorador
 a| 
Se requiere una versión mínima del explorador para que se inicie System Manager o Unified Manager. Las siguientes son las versiones mínimas admitidas:

* Firefox Versión mínima 80
* Chrome versión mínima 89
* Edge versión mínima 90
* Safari versión mínima 14




 a| 
Compatibilidad con unidades SSD NVMe FIPS 140-3 TB
 a| 
Ahora se admiten unidades SSD NVMe certificadas según NetApp, FIPS 140-3-2. Se identificarán correctamente como tales en el perfil de la cabina de almacenamiento y en System Manager.



 a| 
Compatibilidad con caché de lectura de SSD en EF300 y EF600
 a| 
La caché de lectura de SSD ahora se admite en las controladoras EF300 y EF600 si utilizan HDD con una ampliación SAS.



 a| 
Compatibilidad con iSCSI y mirroring remoto asíncrono de Fibre Channel en EF300 y EF600
 a| 
El mirroring remoto asíncrono (ARVM) ahora se admite en las controladoras EF300 y EF600 con volúmenes basados en NVMe y SAS.



 a| 
Admita EF300 y EF600 sin unidades en la bandeja base
 a| 
Ahora se admiten las configuraciones de controladoras EF300 y EF600 sin unidades NVMe en el soporte base.



 a| 
Puertos USB desactivados para todas las plataformas
 a| 
Los puertos USB ahora están deshabilitados en todas las plataformas.

|===