---
permalink: getting-started/learn-video-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, E-Series videos 
summary: Acceda a demostraciones de vídeo para obtener más información sobre los sistemas E-Series. 
---
= Acceda a vídeos de demostración de E-Series
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Acceda a demostraciones de vídeo para obtener más información sobre los sistemas E-Series.



== E-Series: Almacenamiento rápido, sencillo y fiable

En este vídeo se destacan las ventajas clave de usar sistemas E-Series de NetApp en lugar de usar servidores de consumo para almacenamiento.

https://www.youtube.com/embed/FjFkU2z_hIo?rel=0["Vídeo de NetApp: Ventajas clave de usar sistemas E-Series de NetApp en lugar de usar servidores de consumo para almacenamiento"^]



== System Manager: Instalación y configuración sencillas

Esta demostración técnica muestra cómo la interfaz web de SANtricity System Manager permite una configuración y una configuración sencillas de E2800 de NetApp.

https://www.youtube.com/embed/I0W0AjKpCO8?rel=0["Vídeo de NetApp: System Manager de SANtricity: Instalación y configuración sencillas"^]
