---
permalink: config-vmware/configure-multipath-software-concept.html 
sidebar: sidebar 
keywords: multipath software for vmware, express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E4000, EF50, EF80, E-Series, eseries 
summary: Configure el software multivía para que proporcione una ruta redundante a la cabina de almacenamiento en caso de que se interrumpa una de las rutas físicas. 
---
= Cómo funciona la multivía para los hosts de VMware en E-Series
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para proporcionar una ruta redundante a la matriz de almacenamiento, configura el software multivía.

El software multivía proporciona una ruta redundante a la cabina de almacenamiento en caso de que se interrumpa una de las rutas físicas. El software multivía presenta el sistema operativo con un único dispositivo virtual que representa las rutas físicas activas al almacenamiento. El software multipath también administra el proceso de recuperación tras fallos que actualiza el dispositivo virtual.



[[multipathing-policies]]
== Políticas de multivía

A continuación se detallan las políticas de multivía. Para los protocolos FCP, iSCSI y SAS, la configuración predeterminada es Native Multipathing Plug-Ins (NMP). Para NVMe over Fabrics (NVMe over FC, NVMe over RoCE y NVMe over TCP), la configuración predeterminada es High Performance Plug-In (HPP).



[[native-multipathing-plug-ins-nmp]]
=== Complementos de multivía nativos (NMP)

Aplicable solo para los protocolos FCP, iSCSI y SAS, https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-1/vsphere-storage/understanding-multipathing-and-failover-in-the-esxi-environment/vmware-multipathing-module.html["VMware ofrece complementos de multivía nativos (NMP)"^], conocidos como Storage Array Type Plug-ins (SATP), para gestionar las implementaciones de conmutación por error de las cabinas de almacenamiento de proveedores específicos.

El SATP que debes utilizar es *VMW_SATP_ALUA* (esta es la opción predeterminada para E-Series de NetApp). Para más información, consulta https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-1/vsphere-storage/understanding-multipathing-and-failover-in-the-esxi-environment/vmware-satps.html["SATPS de VMware"^].



==== Complementos y políticas de selección de rutas (PSP)

Estos complementos son submódulos del NMP de VMware. El NMP asigna un PSP predeterminado a cada dispositivo lógico en función del tipo de dispositivo. Puedes anular el PSP predeterminado. Para más información, consulta https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-1/vsphere-storage/understanding-multipathing-and-failover-in-the-esxi-environment/viewing-and-managing-storage-paths-on-esxi-hosts/change-the-path-selection-policy.html["Cambiar la política de selección de rutas"^]. El NMP asigna la política de selección de ruta predeterminada VMW_PSP_RR (Round Robin) para dispositivos NetApp. Este es el PSP recomendado.

Para más información, consulta https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-1/vsphere-storage/understanding-multipathing-and-failover-in-the-esxi-environment/vmware-psps.html["Complementos y políticas de selección de rutas de VMware"^].



[[high-performance-plug-in-hpp]]
=== Complemento de alto rendimiento (HPP)

El HPP sustituye al NMP para dispositivos de alta velocidad, como NVMe. El HPP es el complemento predeterminado que reclama destinos NVMe-oF. ESX es compatible con NVMe de extremo a extremo sin emulación y con la emulación de SCSI a NVMe. El HPP solo admite destinos ALUA activos/activos e implícitos.



==== Esquemas de selección de rutas (PSS)

Para admitir la multivía, el HPP utiliza los esquemas de selección de rutas (PSS) a la hora de seleccionar rutas físicas para las solicitudes de E/S. El esquema predeterminado para los dispositivos asignados por el HPP es LB-RR (equilibrio de carga - round robin). Este es el PSS recomendado.

Para obtener más información sobre HPP o PSS, consulta https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-1/vsphere-storage/understanding-multipathing-and-failover-in-the-esxi-environment/vmware-hpp.html["Complemento de alto rendimiento de VMware y esquemas de selección de rutas"^].
