---
permalink: config-vmware/discover-storage-host-task.html 
sidebar: sidebar 
keywords: discover storage ESXi, express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, EF50, EF80, E4000, E-Series, eseries 
summary: Después de asignar volúmenes al host, es posible volver a analizar para que el host detecte y configure los volúmenes para el acceso multivía. 
---
= Descubre el almacenamiento en el host en E-Series para VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Asigna los volúmenes al host. Realiza un nuevo escaneo para que el host detecte y configure los volúmenes para la multivía.

Para obtener información sobre cómo crear hosts y asignar volúmenes, consulta:

* https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-host-manually.html["Crear definiciones de host"^]
* https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-host-cluster.html["Crear clúster de hosts"^]
* https://docs.netapp.com/us-en/e-series-santricity/sm-storage/assign-volumes.html["Asigna volúmenes a los hosts"^]


De forma predeterminada, un host ESXi ejecuta automáticamente una nueva detección cada cinco minutos. Es posible que un volumen aparezca entre el momento en el que se crea y se lo asigne a un host, antes de ejecutar una detección manual. De todos modos, es posible realizar una detección repetida manual para garantizar que todos los volúmenes estén configurados correctamente.

.Pasos
. Asegúrate de que los volúmenes se creen y asignen al host ESXi tal y como se describe en los enlaces anteriores.
. Si se usa una instancia de vCenter Server, añada el host al inventario del servidor.
. Utilice vSphere Client o vSphere Web Client para la conexión directa a vCenter Server o al host ESXi.
. Para obtener instrucciones sobre cómo volver a escanear el almacenamiento en un host ESXi, consulta https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-1/vsphere-storage/managing-esxi-storage-devices/rescan-operations-for-esxi-storage/perform-storage-rescan.html["Realiza un nuevo escaneo del almacenamiento"^].

