---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-delete-trusted-certificates.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Elimine uno o varios certificados que ya no sean necesarios. 
---
= Elimine certificados de confianza
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede eliminar uno o varios certificados que ya no sean necesarios, por ejemplo, un certificado caducado.

.Antes de empezar
Importe el certificado nuevo antes de eliminar el antiguo.


CAUTION: Tenga en cuenta que la eliminación de un certificado intermedio o de raíz puede afectar a varias cabinas de almacenamiento, ya que es posible que estas cabinas compartan los mismos archivos de certificado.

.Pasos
. Seleccione *Gestión de certificados*.
. Seleccione la ficha *Trusted*.
. Seleccione uno o varios certificados de la tabla y, a continuación, haga clic en *Eliminar*.
+

NOTE: La función Eliminar no está disponible para los certificados preinstalados.

+
Se abrirá el cuadro de diálogo Confirmar eliminación de certificado de confianza.

. Confirme la eliminación y haga clic en *Eliminar*.
+
El certificado se eliminará de la tabla.


