---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-clear-staged-os-software.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Puede quitar el software de sistema operativo almacenado temporalmente para garantizar que no se active una versión pendiente de manera accidental más adelante. 
---
= Borre el software de sistema operativo almacenado temporalmente en el complemento de almacenamiento de SANtricity para vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede quitar el software de sistema operativo almacenado temporalmente para garantizar que no se active una versión pendiente de manera accidental más adelante. La eliminación del software de sistema operativo almacenado temporalmente no afecta la versión actual que está en ejecución en las cabinas de almacenamiento.

.Pasos
. En la vista principal, seleccione *gestionar* y, a continuación, elija menú:Centro de actualización[Borrar software SANtricity almacenado temporalmente].
+
Se abre el cuadro de diálogo Borrar software SANtricity almacenado temporalmente, donde se enumeran todos los sistemas de almacenamiento detectados con software o NVSRAM pendiente.

. Si es necesario, puede filtrar u ordenar los sistemas de almacenamiento de la lista, de modo que pueda ver todos los sistemas que tienen software almacenado temporalmente.
. Marque las casillas de comprobación de los sistemas de almacenamiento con software pendiente que desea borrar.
. Haga clic en *Borrar*.
+
El estado de la operación se muestra en el cuadro de diálogo.


