---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-rename-storage-array-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Cambie el nombre de un grupo de cabinas de almacenamiento si el nombre actual ya no es significativo o no corresponde. 
---
= Cambiar el nombre de un grupo de cabinas de almacenamiento
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es posible cambiar el nombre de un grupo de cabinas de almacenamiento si el nombre actual ya no es significativo o no corresponde.

.Acerca de esta tarea
Tenga en cuenta estas directrices.

* Un nombre puede consistir de letras, números y los caracteres especiales de subrayado (_), guión (-) y almohadilla (#). Si elige otros caracteres, aparece un mensaje de error. Se le solicitará que elija otro nombre.
* El nombre puede tener 30 caracteres como máximo. Los espacios iniciales o finales del nombre se eliminan.
* Use un nombre único, significativo, que sea fácil de entender y de recordar.
* Evite nombres arbitrarios o nombres que rápidamente pueden perder sentido en el futuro.


.Pasos
. En la ventana principal, seleccione *gestionar* y seleccione el grupo de cabinas de almacenamiento al que desea cambiarle el nombre.
. Seleccione menu:gestionar grupos[Cambiar nombre de grupo de cabinas de almacenamiento].
. En el campo *Nombre del grupo*, escriba un nuevo nombre para el grupo.
. Haga clic en *Cambiar nombre*.

