---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-configuration-settings-for-a-pool.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Edite la configuración de un pool, incluidos el nombre, la configuración de alertas de capacidad, las prioridades de modificación y la capacidad de conservación. 
---
= Cambiar la configuración de un pool
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La configuración de un pool se puede editar, incluido el nombre, las alertas de capacidad, las prioridades de modificación y la capacidad de conservación.

.Acerca de esta tarea
En esta tarea, se describe cómo cambiar la configuración de un pool.


NOTE: No se puede cambiar el nivel de RAID de un pool mediante la interfaz del plugin. El complemento configura automáticamente los pools como RAID 6.

.Pasos
. En la página gestionar, seleccione la cabina de almacenamiento con el pool.
. Seleccione MENU:Provisioning[Configure Pools and Volume Groups].
. Seleccione el pool que desea editar y, a continuación, haga clic en *Ver/editar configuración*.
+
Se muestra el cuadro de diálogo Configuración del pool.

. Seleccione la ficha *Configuración* y, a continuación, edite la configuración del pool según corresponda.
+
.Detalles del campo
[%collapsible]
====
[cols="25h,~"]
|===
| Ajuste | Descripción 


 a| 
Nombre
 a| 
El nombre del pool proporcionado por el usuario se puede modificar. Es necesario especificar un nombre para el pool.



 a| 
Alertas de capacidad
 a| 
Las notificaciones de alerta se pueden enviar cuando la capacidad libre de un pool alcanza o supera un umbral especificado. Cuando los datos almacenados en el pool superan el umbral especificado, el plugin envía un mensaje, lo que le da tiempo para agregar más espacio de almacenamiento o eliminar objetos innecesarios. Las alertas se muestran en el área Notificaciones de la consola y se pueden enviar del servidor a los administradores por correo electrónico y mensajes de captura SNMP. Se pueden definir las siguientes alertas sobre capacidad:

** *Alerta crítica* -- esta alerta crítica le avisa cuando la capacidad libre en el pool alcanza o supera el umbral especificado. Se deben usar los controles de desplazamiento para ajustar el porcentaje del umbral. Seleccione la casilla de comprobación para deshabilitar esta notificación.
** *Alerta temprana* -- esta alerta anticipada le notifica cuando la capacidad libre en un pool está alcanzando un umbral especificado. Se deben usar los controles de desplazamiento para ajustar el porcentaje del umbral. Seleccione la casilla de comprobación para deshabilitar esta notificación.




 a| 
Prioridades de modificación
 a| 
Se pueden especificar niveles de prioridad para las operaciones de modificación en un pool con respecto al rendimiento del sistema. Si se le otorga una mayor prioridad a las operaciones de modificación de un pool, se agiliza el tiempo de finalización de la operación, pero puede ralentizar el rendimiento de I/o del host. Si se otorga una prioridad, las operaciones tardan más tiempo, pero el rendimiento de I/o del host se ve menos afectado. Se puede elegir entre cinco niveles de prioridad: Mínimo, bajo, medio, alto y máximo. Cuanto más alto sea el nivel de prioridad, mayor será el impacto sobre las operaciones de I/o del host y el rendimiento del sistema.

** *Prioridad de reconstrucción crítica* -- esta barra deslizante determina la prioridad de una operación de reconstrucción de datos cuando múltiples fallos de unidad dan lugar a una condición en la que algunos datos no tienen redundancia y un fallo de unidad adicional puede resultar en la pérdida de datos.
** *Prioridad de reconstrucción degradada* -- esta barra deslizante determina la prioridad de la operación de reconstrucción de datos cuando se ha producido un fallo de unidad, pero los datos siguen teniendo redundancia y un fallo de unidad adicional no provoca la pérdida de datos.
** *Prioridad de operación en segundo plano* -- esta barra deslizante determina la prioridad de las operaciones en segundo plano del pool que ocurren mientras el pool está en estado óptimo. Entre estas operaciones se incluyen la expansión dinámica de volúmenes (DVE), el formato de disponibilidad instantánea (IAF) y la migración de datos a una unidad reemplazada o añadida.




 a| 
Capacidad de conservación ("capacidad de optimización" para EF600 o EF300)
 a| 
*Capacidad de conservación* -- se puede definir la cantidad de unidades para determinar la capacidad que se reserva en el pool para admitir posibles fallos de unidad. Cuando se produce un fallo de unidad, la capacidad de conservación se usa para contener los datos reconstruidos. Los pools utilizan la capacidad de conservación durante el proceso de reconstrucción de datos en lugar de las unidades de repuesto, que se utilizan en los grupos de volúmenes. Use los controles de desplazamiento para ajustar la cantidad de unidades. La capacidad de conservación del pool aparece junto al cuadro de desplazamiento en función de la cantidad de unidades. Tenga en cuenta la siguiente información acerca de la capacidad de conservación.

** Debido a que la capacidad de conservación se sustrae de la capacidad libre total de un pool, la cantidad de capacidad que se reserva afecta a la cantidad de capacidad libre disponible para crear volúmenes. Si se especifica el valor 0 para la capacidad de conservación, se utiliza toda la capacidad libre del pool para la creación del volumen.
** Si se disminuye la capacidad de conservación, aumenta la capacidad que se puede usar para los volúmenes del pool.


*Capacidad de optimización adicional (sólo cabinas EF600 y EF300)*: Cuando se crea un pool, se genera una capacidad de optimización recomendada que proporciona un equilibrio entre la capacidad disponible y el rendimiento y la vida útil de la unidad. Puede ajustar este equilibrio moviendo el control deslizante a la derecha para mejorar el rendimiento y el deterioro de la unidad a expensas de la capacidad disponible aumentada, o bien moviéndolo a la izquierda para aumentar la capacidad disponible a costa de un mejor rendimiento y de la vida útil de la unidad. Las unidades SSD tendrán una mayor vida útil y mejor rendimiento de escritura máximo cuando una parte de su capacidad no está asignada. Para las unidades asociadas con un pool, la capacidad sin asignar consta de la capacidad de conservación de un pool, la capacidad libre (capacidad que no usan los volúmenes) y una parte de la capacidad utilizable como capacidad de optimización adicional. La capacidad de optimización adicional garantiza un nivel mínimo de capacidad de optimización mediante la reducción de la capacidad utilizable, y, como tal, no está disponible para la creación de volúmenes.

|===
====
. Haga clic en *Guardar*.

