---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-pool-automatically.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Es posible crear pools automáticamente cuando el sistema detecta al menos 11 unidades sin asignar o detecta una unidad sin asignar que es elegible para un pool existente. 
---
= Cree un pool automáticamente en el complemento de almacenamiento de SANtricity para vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es posible crear pools automáticamente cuando el sistema detecta al menos 11 unidades sin asignar o detecta una unidad sin asignar que es elegible para un pool existente. Un pool es un conjunto de unidades agrupadas lógicamente.

.Antes de empezar
Para abrir el cuadro de diálogo Configuración automática del pool se debe presentar alguna de estas condiciones:

* Se detectó al menos una unidad sin asignar que se puede añadir a un pool existente con tipos de unidades similares.
* Se detectaron once (11) o más unidades sin asignar que se pueden usar para crear un pool nuevo (si no se pueden añadir al pool existente debido a que los tipos de unidad son distintos).


.Acerca de esta tarea
Es posible usar la creación automática de pools para configurar fácilmente todas las unidades sin asignar en la cabina de almacenamiento en un pool y añadir unidades a pools existentes.

Se debe recordar lo siguiente:

* Si se añaden unidades a una cabina de almacenamiento, el sistema automáticamente detecta las unidades y solicita la creación de un pool único o varios pools según el tipo de unidad y la configuración actual.
* Si se definieron pools previamente, el sistema automáticamente ofrece la opción de añadir las unidades compatibles a un pool existente. Si se añaden unidades nuevas a un pool existente, el sistema automáticamente redistribuye los datos conforme a la capacidad nueva, que ahora incluye las unidades nuevas que se añadieron.
* Al configurar una cabina de almacenamiento EF600 o EF300, asegúrese de que cada controladora tenga acceso a un número igual de unidades en las primeras 12 ranuras y un número igual de unidades en las últimas 12 ranuras. Esta configuración ayuda a las controladoras a usar ambos autobuses PCIe de la unidad de forma más eficaz. Para la creación de un pool, se deben usar todas las unidades de la cabina de almacenamiento.


.Pasos
. En la página gestionar, seleccione la cabina de almacenamiento para el pool.
. Seleccione MENU:Provisioning[Configure Pools and Volume Groups].
. Seleccione MENU:More[Iniciar configuración automática del pool].
+
En la tabla de resultados, se muestra una lista de los pools nuevos, los pools existentes con unidades añadidas o ambos. El nombre de un pool nuevo es, de forma predeterminada, un número secuencial.

+
Observe que el sistema hace lo siguiente:

+
** Crea un pool único si hay una cantidad suficiente de unidades del mismo tipo (HDD o SSD) y con capacidad similar.
** Crea varios pools si la capacidad sin asignar consta de diferentes tipos de unidades.
** Añade las unidades a un pool existente si ya hay un pool definido en la cabina de almacenamiento y si se añaden unidades nuevas del mismo tipo al pool.
** Añade las unidades del mismo tipo al pool existente y usa los otros tipos de unidades para crear distintos pools si las unidades nuevas son de distinto tipo.


. Para cambiar el nombre de una nueva agrupación, haga clic en el icono *Editar* (el lápiz).
. Para ver las características adicionales del pool, ubique el cursor sobre el icono Detalles (la página) o toque el icono.
+
Se muestra información acerca del tipo de unidad, la función de seguridad, la funcionalidad Data Assurance (DA), la protección contra pérdida de bandeja y la protección contra pérdida de cajón.

+
Para las cabinas de almacenamiento EF600 y EF300, también se muestran las configuraciones para el aprovisionamiento de recursos y los tamaños de bloque de volúmenes.

. Haga clic en *Aceptar*.

