---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-storage-configuration-settings.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Importe la configuración de almacenamiento de una cabina de almacenamiento en otras cabinas de almacenamiento. 
---
= Importe los ajustes de configuración de almacenamiento en el complemento de almacenamiento de SANtricity para vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es posible importar la configuración de almacenamiento de una cabina de almacenamiento en otras cabinas de almacenamiento. Esta operación en lote permite ahorrar tiempo cuando se necesitan configurar varias matrices en la red.

.Antes de empezar
Asegúrese de que:

* El almacenamiento se configura en la instancia de System Manager correspondiente a la cabina de almacenamiento que se quiere usar como origen.
* La configuración actual de las cabinas de almacenamiento objetivo cuenta con una copia de seguridad en System Manager (menú:Configuración[sistema > Guardar configuración de la cabina de almacenamiento]).
* Ha revisado los requisitos para replicar configuraciones de almacenamiento en link:vc-olh-import-settings-overview.html["Información general sobre la configuración de importación"].
* Las cabinas de origen y objetivo deben cumplir con los siguientes requisitos:
+
** Las bandejas donde residan las controladoras deben ser idénticas.
** Los ID de bandeja deben ser idénticos.
** Las bandejas de expansión deben llenarse en las mismas ranuras con los mismos tipos de unidad.
** El tipo de compartimento RBOD debe ser idéntico.
** Las HIC, incluidas las capacidades de garantía de datos del host, deben ser idénticas.
** Las cabinas objetivo deben tener el estado óptimo.
** La capacidad de volumen de la cabina objetivo es mayor que la capacidad de la cabina de origen.


* Debe considerar las siguientes restricciones:
+
** No se admite la importación de una configuración doble a una simple; sí se admite la configuración simple a doble.
** Un volumen de pool de discos de 64 TB o mayor en la cabina de origen impide el proceso de importación en las cabinas objetivo.




.Acerca de esta tarea
La configuración importada incluye volúmenes configurados (solo volúmenes gruesos y que no pertenecen al repositorio), grupos de volúmenes, pools y asignaciones de unidades de repuesto.

.Pasos
. En la página gestionar, haga clic en MENU:Actions[Import Settings].
+
Se abre el asistente Importar configuración.

. En el cuadro de diálogo Seleccionar configuración, seleccione *Configuración de almacenamiento* y, a continuación, haga clic en *Siguiente*.
+
Se abre un cuadro de diálogo para seleccionar la cabina de almacenamiento.

. En el cuadro de diálogo Seleccionar origen, seleccione la matriz con la configuración que desea importar y, a continuación, haga clic en *Siguiente*.
. En el cuadro de diálogo Seleccionar objetivos, elija una o más cabinas para que reciban la nueva configuración.
+

NOTE: Las cabinas de almacenamiento con una versión de firmware inferior a 8.50 no están disponibles y no pueden seleccionarse. Además, una matriz no aparece en este cuadro de diálogo si el plugin no puede comunicarse con esa matriz (por ejemplo, si está desconectada o si tiene problemas de red o con un certificado o una contraseña).

. Haga clic en *Finalizar*.
+
En la página Operaciones, se muestran los resultados de la operación de importación. Si se produce un error en la operación, puede hacer clic en la fila para ver más información.



.Resultado
Las cabinas de almacenamiento objetivo ahora están configuradas con los mismos ajustes de almacenamiento que la cabina de origen.
