---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-storage-array-passwords.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Actualice las contraseñas que se utilizan para ver y acceder a las cabinas de almacenamiento en el complemento de almacenamiento para vCenter. 
---
= Cambie las contraseñas de las cabinas de almacenamiento en el complemento de almacenamiento SANtricity para vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede actualizar las contraseñas que se utilizan para ver y acceder a las cabinas de almacenamiento en el complemento de almacenamiento para vCenter.

.Antes de empezar
Debe conocer la contraseña actual de la cabina de almacenamiento que se estableció en System Manager.

.Acerca de esta tarea
En esta tarea, debe introducir la contraseña actual de una cabina de almacenamiento para poder acceder a esta en el plugin. Esto puede ser necesario si se modificó la contraseña de la cabina en System Manager.

.Pasos
. En la página *gestionar*, seleccione una o más matrices de almacenamiento.
. Seleccione menú:tareas no comunes[proporcionar contraseñas de cabina de almacenamiento].
. Introduzca la contraseña o las contraseñas de cada cabina de almacenamiento y haga clic en *Guardar*.

