---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-host-creation-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Para gestionar el almacenamiento con el complemento de almacenamiento para vCenter, debe detectar o definir cada host de la red. 
---
= Información general de creación de hosts
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Para gestionar el almacenamiento con el complemento de almacenamiento para vCenter, debe detectar o definir cada host de la red. Un host es un servidor que envía I/o a un volumen de una cabina de almacenamiento.



== Creación manual de hosts

La creación de un host es uno de los pasos necesarios para indicar a la cabina de almacenamiento qué hosts están conectados a ella y para permitir el acceso de I/o a los volúmenes. Un host se puede crear manualmente.

* *Manual* -- durante la creación manual de host, usted asocia identificadores de puerto de host seleccionándolos de una lista o introduciéndolos manualmente. Después de crear un host, puede asignar volúmenes a él o añadirlo a un clúster de hosts si el objetivo es compartir el acceso a los volúmenes.




== Cómo se asignan volúmenes

Para que un host envíe I/o a un volumen, se debe asignar el volumen. Es posible seleccionar un host o un clúster de hosts cuando se crea un volumen, o asignar un volumen a un host o clúster de hosts más adelante. Un clúster de hosts es un grupo de hosts. Se crea un clúster de hosts para facilitar la asignación de los mismos volúmenes en varios hosts.

La asignación de volúmenes a hosts es flexible y permite satisfacer necesidades de almacenamiento específicas.

* *Host autónomo, no parte de un cluster host* -- puede asignar un volumen a un host individual. Un solo host puede acceder al volumen.
* *Clúster de host* -- puede asignar un volumen a un clúster de hosts. Todos los hosts del clúster de hosts pueden acceder al volumen.
* *Host dentro de un cluster host* -- puede asignar un volumen a un host individual que forma parte de un cluster de host. Aunque el host forma parte de un clúster de hosts, solo el host individual puede acceder al volumen y no ningún otro host del clúster de hosts.


Cuando se crean volúmenes, se asignan automáticamente números de unidad lógica (LUN). Los LUN actúan como dirección entre el host y la controladora durante las operaciones de I/O. Es posible cambiar el LUN después de crear un volumen.
