---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-assign-volumes-to-hosts.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Se debe asignar un volumen a un host o un clúster de hosts para poder usarlo con operaciones de I/O. 
---
= Asigne volúmenes a los hosts en el plugin de almacenamiento de SANtricity para vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se debe asignar un volumen a un host o un clúster de hosts para poder usarlo con operaciones de I/O.

.Antes de empezar
Tenga en cuenta estas directrices al asignar volúmenes a hosts:

* Es posible asignar un volumen a un solo host o clúster de hosts al mismo tiempo.
* Los volúmenes asignados se comparten entre controladoras de la cabina de almacenamiento.
* El host o un clúster de hosts no pueden usar el mismo número de unidad lógica (LUN) dos veces para acceder a un volumen. Se debe usar un LUN único.
* En el caso de los grupos de volúmenes nuevos, si espera hasta que se crean e inicializan todos los volúmenes antes de asignarles un host, se reduce el tiempo de inicialización del volumen. Tenga en cuenta que, una vez asignado un volumen asociado con el grupo de volúmenes, todos los volúmenes revertirán a la inicialización más lenta.


.Acerca de esta tarea
Una asignación de volumen otorga acceso a un host o un clúster de hosts al volumen en una cabina de almacenamiento.

Todos los volúmenes sin asignar se muestran durante esta tarea, pero las funciones para hosts con o sin Data Assurance (DA) se aplican de la siguiente manera:

* Para un host compatible con DA, es posible seleccionar volúmenes con o sin LA función DA habilitada.
* Para un host no compatible con DA, si selecciona un volumen con la función DA habilitada, una advertencia indica que el sistema debe desactivar automáticamente DA antes de asignar el volumen al host.
+
La asignación de un volumen falla en las siguientes condiciones:

* Todos los volúmenes están asignados.
* El volumen ya está asignado a otro host o clúster de hosts. La capacidad para asignar un volumen no está disponible debido a las siguientes condiciones:
* No existen hosts ni clústeres de hosts válidos.
* No se definieron identificadores de puertos para el host.
* Se definieron todas las asignaciones de volúmenes.


.Pasos
. En la página gestionar, seleccione la cabina de almacenamiento con la conexión del host.
. Seleccione MENU:Provisioning[Configure hosts].
+
Se abre la página Configurar hosts.

. Seleccione el host o clúster de hosts al que desea asignar volúmenes y, a continuación, haga clic en *asignar volúmenes*.
+
Se muestra un cuadro de diálogo que enumera todos los volúmenes que pueden asignarse. Es posible seleccionar cualquiera de las columnas o escribir un elemento en el cuadro Filtrar para facilitar la búsqueda de volúmenes en particular.

. Seleccione la casilla de comprobación ubicada junto a cada volumen que desea asignar, o bien seleccione la casilla de comprobación en el encabezado de la tabla para seleccionar todos los volúmenes.
. Haga clic en *asignar* para completar la operación.


.Resultados
Después de asignar correctamente uno o varios volúmenes a un host o un clúster de hosts, el sistema realiza las siguientes acciones:

* El volumen asignado recibe el próximo número de unidad lógica disponible. El host utiliza el número de unidad lógica para acceder al volumen.
* El nombre del volumen proporcionado por el usuario aparece en los listados de volúmenes asociados al host. Si corresponde, el volumen de acceso configurado de fábrica también aparece en los listados de volúmenes asociados al host.

