---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-perform-pre-upgrade-health-check.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Una comprobación del estado se ejecuta como parte del proceso de actualización, pero también es posible ejecutarla por separado, antes de comenzar. 
---
= Realice la comprobación del estado previa a la actualización en el complemento de almacenamiento de SANtricity para vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Una comprobación del estado se ejecuta como parte del proceso de actualización, pero también es posible ejecutarla por separado, antes de comenzar. La comprobación del estado evalúa los componentes de la cabina de almacenamiento para garantizar que se pueda proceder con la actualización.

* Pasos*

. En la vista principal, seleccione *gestionar* y, a continuación, elija Menú:Centro de actualización[Comprobación del estado previa a la actualización].
+
Se abre el cuadro de diálogo Comprobación del estado previa a la actualización, donde se enumeran todos los sistemas de almacenamiento detectados.

. Si es necesario, puede filtrar u ordenar los sistemas de almacenamiento de la lista, de modo que pueda ver todos los sistemas que están actualmente en estado óptimo.
. Marque las casillas de comprobación de los sistemas de almacenamiento que quiere incluir en la comprobación del estado.
. Haga clic en *Inicio*.
+
Mientras se lleva a cabo la comprobación del estado, se muestra el progreso en el cuadro de diálogo.

. Una vez finalizada la comprobación del estado, puede hacer clic en los tres puntos (...) a la derecha de cada fila para ver más información y realizar otras tareas.



NOTE: Si ocurre un error en la comprobación del estado de alguna cabina, puede omitir esa cabina en particular y continuar la actualización de las otras cabinas. Otra opción es detener el proceso por completo y solucionar los problemas de las cabinas que presentaron errores.
