---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-array-groups-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Gestione la infraestructura física y virtualizada agrupando un conjunto de cabinas de almacenamiento. 
---
= Información general sobre grupos de cabinas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede gestionar la infraestructura física y virtualizada en el complemento de almacenamiento para vCenter mediante la agrupación de un conjunto de cabinas de almacenamiento. Las cabinas de almacenamiento pueden agruparse de modo que sea más sencillo ejecutar las tareas de supervisión o generación de informes.

Tipos de grupos de cabinas de almacenamiento:

* *Todo el grupo* -- el grupo todo es el grupo predeterminado e incluye todas las matrices de almacenamiento detectadas en su organización. Es posible acceder al grupo desde la vista principal.
* *Grupo creado por el usuario* -- Un grupo creado por el usuario incluye las matrices de almacenamiento que selecciona manualmente para agregar a ese grupo. Es posible acceder a este tipo de grupo desde la vista principal.

