---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Es posible crear un grupo de volúmenes para uno o varios volúmenes a los que el host puede acceder. 
---
= Cree un grupo de volúmenes
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es posible crear un grupo de volúmenes para uno o varios volúmenes a los que el host puede acceder. Un grupo de volúmenes es un contenedor para volúmenes con características compartidas, como nivel de RAID y capacidad.

.Antes de empezar
Revise las siguientes directrices:

* Se necesita al menos una unidad sin asignar.
* Existen límites en cuanto a la cantidad de capacidad de unidad que se puede tener en un único grupo de volúmenes. Estos límites varían según el tipo de host.
* Para habilitar la protección de bandeja/cajón, debe crear un grupo de volúmenes que utilice unidades ubicadas en al menos tres bandejas o cajones, a menos que utilice RAID 1, donde dos bandejas/cajones es el valor mínimo.
* Al configurar una cabina de almacenamiento EF600 o EF300, asegúrese de que cada controladora tenga acceso a un número igual de unidades en las primeras 12 ranuras y un número igual de unidades en las últimas 12 ranuras. Esta configuración ayuda a las controladoras a usar ambos autobuses PCIe de la unidad de forma más eficaz. El sistema actualmente permite seleccionar unidades en la función Avanzada al crear un grupo de volúmenes.


Revise de qué manera la selección del nivel de RAID afecta a la capacidad resultante del grupo de volúmenes.

* Si selecciona RAID 1, debe añadir dos unidades al mismo tiempo para asegurarse de que se haya seleccionado una pareja reflejada. Las operaciones de mirroring y segmentación (denominada RAID 10 o RAID 1+0) se logran cuando se seleccionan cuatro o más unidades.
* Si selecciona RAID 5, debe añadir un mínimo de tres unidades para crear el grupo de volúmenes.
* Si selecciona RAID 6, debe añadir un mínimo de cinco unidades para crear el grupo de volúmenes.


.Acerca de esta tarea
Durante la creación de un grupo de volúmenes, se determinan las características de grupo, como la cantidad de unidades, la funcionalidad de seguridad, la funcionalidad Data Assurance (DA), la protección contra pérdida de bandeja y la protección contra pérdida de cajón.

Para las cabinas de almacenamiento EF600 y EF300, las configuraciones también incluyen aprovisionamiento de recursos, tamaños de bloques de unidades y tamaños de bloques de volúmenes.


NOTE: Con unidades de mayor capacidad y la capacidad para distribuir volúmenes en controladoras, crear más de un volumen por grupo de volúmenes es una buena manera de utilizar la capacidad de almacenamiento y proteger los datos.

.Pasos
. En la página gestionar, seleccione la cabina de almacenamiento para el grupo de volúmenes.
. Seleccione MENU:Provisioning[Configure Pools and Volume Groups].
. Haga clic en MENU:Create[Grupo de volúmenes].
+
Se muestra el cuadro de diálogo Crear un grupo de volúmenes.

. Escriba un nombre para el grupo de volúmenes.
. Seleccione el nivel de RAID que mejor cumpla sus requisitos de almacenamiento y protección de datos. Aparece la tabla de candidatos del grupo de volúmenes, donde se muestran solo los candidatos compatibles con el nivel de RAID seleccionado.
. (Opcional) Si tiene más de un tipo de unidad en la cabina de almacenamiento, seleccione el tipo de unidad que desea usar.
+
Aparece la tabla de candidatos del grupo de volúmenes, donde se muestran solo los candidatos compatibles con el tipo de unidad y el nivel de RAID seleccionados.

. (Opcional) es posible seleccionar el método automático o el método manual para definir las unidades que se utilizarán en el grupo de volúmenes. El método automático es la selección predeterminada.
+

CAUTION: No use el método manual a menos que sea un experto que comprenda la redundancia de unidades y las configuraciones de unidades óptimas.

+
Para seleccionar unidades manualmente, haga clic en el enlace *selección manual de unidades (avanzada)*. Al hacer clic en esta opción, cambia a *Seleccionar automáticamente unidades (avanzadas)*.

+
El método manual permite seleccionar las unidades específicas que componen el grupo de volúmenes. Es posible seleccionar unidades sin asignar específicas para obtener la capacidad requerida. Si la cabina de almacenamiento contiene unidades con tipos de medios diferentes o tipos de interfaces diferentes, es posible seleccionar solo la capacidad sin configurar de un solo tipo de unidad para crear el grupo de volúmenes.

. Según las características de la unidad que se muestran, seleccione las unidades que desea usar en el grupo de volúmenes y, a continuación, haga clic en *Crear*.


Las características de la unidad que se muestran dependen de si se seleccionó el método automático o el método manual. Para obtener más información, consulte la documentación de SANtricity System Manager: https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-volume-group.html["Cree un grupo de volúmenes"^].
