---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-do-i-need-to-know-about-the-resource-provisioned-volumes-feature.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: El aprovisionamiento de recursos es una función disponible en las cabinas de almacenamiento EF300 y EF600, lo que permite poner en uso los volúmenes de inmediato sin proceso de inicialización en segundo plano. 
---
= ¿Qué debo saber acerca de la función de volúmenes aprovisionados mediante recursos?
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El aprovisionamiento de recursos es una función disponible en las cabinas de almacenamiento EF300 y EF600, lo que permite poner en uso los volúmenes de inmediato sin proceso de inicialización en segundo plano.


NOTE: La función de aprovisionamiento de recursos no está disponible en este momento. En algunas vistas, los componentes pueden notificarse como compatibles con el aprovisionamiento de recursos, pero se ha deshabilitado la capacidad para crear volúmenes aprovisionados mediante recursos hasta que se pueda volver a habilitar en una actualización futura.



== Volúmenes aprovisionados mediante recursos

Un volumen aprovisionado por recursos es un volumen grueso de un grupo de volúmenes SSD o pool, donde se asigna capacidad de la unidad (asignada al volumen) cuando se crea el volumen, pero los bloques de unidades no se asignan (anula la asignación). En comparación, en un volumen grueso tradicional, todos los bloques de unidades se asignan o se asignan durante una operación de inicialización de volúmenes en segundo plano para inicializar los campos de información de protección de Data Assurance y para hacer que la paridad de datos y RAID sea coherente en cada franja de RAID. Con un volumen aprovisionado, no existe una inicialización en segundo plano vinculada al tiempo. En su lugar, cada franja RAID se inicializa con la primera escritura en un bloque de volumen en la franja.

Los volúmenes aprovisionados mediante recursos solo se admiten en los grupos de volúmenes SSD y pools, donde todas las unidades del grupo o pool admiten la funcionalidad de recuperación de error de bloque lógico no escrito o desasignado (DULBE). Cuando se crea un volumen aprovisionado por recursos, todos los bloques de unidades asignados al volumen se desasignan (desasignan). Asimismo, los hosts pueden desasignar bloques lógicos del volumen mediante el comando Gestión de conjuntos de datos de NVMe. Si se desasignan bloques, es posible mejorar la vida útil de las unidades de estado sólido y aumentar el rendimiento de escritura máximo. La mejora varía en función del modelo y la capacidad de cada unidad.



== Habilitar y deshabilitar la función

El aprovisionamiento de recursos está habilitado de forma predeterminada en sistemas donde las unidades admiten DULBE. Puede deshabilitar esa configuración predeterminada en Pools y grupos de volúmenes. La deshabilitación del aprovisionamiento de recursos es una acción permanente para los volúmenes existentes y no se puede revertir (es decir, no se puede volver a habilitar el aprovisionamiento de recursos para estos grupos de volúmenes y pools).

Sin embargo, si desea volver a habilitar el aprovisionamiento de recursos para los volúmenes nuevos que cree, puede hacerlo en menu:Settings[System]. Tenga en cuenta que cuando se vuelve a habilitar el aprovisionamiento de recursos, solo se ven afectados los grupos de volúmenes y pools recién creados. Todos los grupos de volúmenes y pools existentes se mantendrán sin cambios. Si lo desea, también puede deshabilitar el aprovisionamiento de recursos de nuevo desde MENU:Settings[System].
