---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-export-certificates.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Exportar un certificado para ver todos sus detalles. 
---
= Exportar certificados
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible exportar un certificado para ver todos sus detalles.

.Antes de empezar
Para abrir el archivo exportado, debe contar con una aplicación para visualización de certificados.

.Pasos
. Seleccione *Gestión de certificados*.
. Seleccione una de las siguientes pestañas:
+
** *Administración* -- muestra el certificado para el sistema que aloja el plugin. Un certificado de gestión puede estar autofirmado o estar aprobado por una CA. Permite un acceso seguro al plugin.
** *Trusted* -- muestra certificados a los que el plugin puede acceder para matrices de almacenamiento y otros servidores remotos, como un servidor LDAP. Los certificados pueden emitirse mediante una CA o estar autofirmados.


. Seleccione un certificado de la página y, a continuación, haga clic en los tres puntos al final de la fila.
. Haga clic en *Exportar* y guarde el archivo de certificado.
. Abra el archivo en la aplicación para visualización de certificados.

