---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-manage-software-repository.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Puede ver y gestionar un repositorio de software, que enumera todos los archivos de software asociados con el complemento de almacenamiento para vCenter. 
---
= Gestionar el repositorio de software
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede ver y gestionar un repositorio de software, que enumera todos los archivos de software asociados con el complemento de almacenamiento para vCenter.

.Antes de empezar
Si utiliza el repositorio para añadir archivos de sistema operativo SANtricity, asegúrese de que estén disponibles en el sistema local.

.Acerca de esta tarea
Puede utilizar la opción gestionar repositorio de software de sistema operativo SANtricity para importar uno o más archivos de sistema operativo al sistema host donde se ejecuta el plugin. También puede optar por eliminar uno o varios de los archivos de sistema operativo que están disponibles en el repositorio de software.

.Pasos
. En la vista principal, seleccione *gestionar* y, a continuación, elija Menú:Centro de actualización[gestionar el repositorio de software de SANtricity].
+
Se muestra el cuadro de diálogo gestionar el repositorio de software de sistema operativo SANtricity.

. Ejecute una de las siguientes acciones:
+
** *Importar:*
+
... Haga clic en *Importar*.
... Haga clic en *examinar* y, a continuación, desplácese hasta la ubicación en la que residen los archivos del sistema operativo que desea agregar. Los archivos de sistema operativo tienen un nombre similar a `N2800-830000-000.dlp`.
... Seleccione uno o más archivos de sistema operativo que desee agregar y, a continuación, haga clic en *Importar*.


** *Eliminar:*
+
... Seleccione uno o varios archivos de sistema operativo que desee quitar del repositorio de software.
... Haga clic en *Eliminar*.






.Resultado
Si seleccionó Importar, los archivos se cargan y se validan. Si seleccionó Eliminar, los archivos se quitan del repositorio de software.
