---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-provisioning-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Se pueden crear contenedores de datos, denominados volúmenes, para que el host pueda acceder al almacenamiento de la cabina. 
---
= Información general de aprovisionamiento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En el complemento de almacenamiento para vCenter, puede crear contenedores de datos, denominados volúmenes, de modo que el host pueda acceder al almacenamiento de la cabina.



== Tipos de volúmenes y características

Los volúmenes son contenedores de datos que gestionan y organizan el espacio de almacenamiento en la cabina de almacenamiento.

Es posible crear volúmenes a partir de la capacidad de almacenamiento disponible en la cabina de almacenamiento, lo que ayuda a organizar los recursos del sistema. El concepto de "volúmenes" es similar a usar carpetas o directorios en un equipo para organizar archivos con el fin de agilizar el acceso.

Los volúmenes son la única capa de datos visible para los hosts. En un entorno SAN, los volúmenes se asignan a números de unidad lógica (LUN). Estos LUN conservan los datos de usuario a los que se puede acceder mediante uno o varios de los protocolos de acceso de host compatibles con la cabina de almacenamiento, incluidos FC, iSCSI y SAS.

Cada volumen de un pool o grupo de volúmenes puede tener sus propias características individuales según los tipos de datos se almacenarán en el volumen. Algunas de esas características son:

* *Tamaño de segmento* -- un segmento es la cantidad de datos en kilobytes (KiB) que se almacenan en una unidad antes de que la matriz de almacenamiento pase a la siguiente unidad de la franja (grupo RAID). El tamaño del segmento es igual o menor que la capacidad del grupo de volúmenes. El tamaño del segmento es fijo y no se puede cambiar para los pools.
* *Capacidad* -- se crea un volumen a partir de la capacidad libre disponible en un pool o grupo de volúmenes. Para poder crear un volumen, el pool o el grupo de volúmenes ya deben existir y debe haber suficiente capacidad libre para crear el volumen.
* *Propiedad de controlador* -- todas las matrices de almacenamiento pueden tener uno o dos controladores. En una configuración de controladora única, una sola controladora gestiona la carga de trabajo del volumen. En una configuración de controladora doble, un volumen tiene una controladora preferida (A o B) que es "propietaria" del volumen. En una configuración de controladora doble, la propiedad del volumen se ajusta automáticamente mediante la función Automatic Load Balancing para corregir cualquier problema con el equilibrio de carga cuando las cargas de trabajo cambian según la controladora. La función Automatic Load Balancing proporciona equilibrio de cargas de trabajo de I/o automatizado y garantiza que el tráfico de I/o entrante desde los hosts se gestione de manera dinámica y se equilibre entre ambas controladoras.
* *Asignación de volumen* -- puede dar acceso de host a un volumen ya sea al crear el volumen o posteriormente. El acceso a todos los hosts se gestiona mediante un número de unidad lógica (LUN). Los hosts detectan LUN que, a su vez, se asignan a volúmenes. Si va a asignar un volumen a varios hosts, use software de clustering para asegurarse de que el volumen esté disponible para todos los hosts.
+
El tipo de host puede tener límites específicos en lo que respecta a la cantidad de volúmenes a los que puede acceder el host. Tenga presente este límite cuando cree volúmenes que utilizará un host en particular.

* *Aprovisionamiento de recursos* -- para matrices de almacenamiento EF600 o EF300, puede especificar que los volúmenes se utilicen inmediatamente sin ningún proceso de inicialización en segundo plano. Un volumen aprovisionado por recursos es un volumen grueso de un grupo de volúmenes SSD o pool, donde se asigna capacidad de la unidad (asignada al volumen) cuando se crea el volumen, pero los bloques de unidades no se asignan (anula la asignación).
* *Nombre descriptivo* -- se puede nombrar un volumen cualquiera que sea su nombre, pero se recomienda que el nombre sea descriptivo.


Durante la creación de volúmenes, se asigna capacidad a cada volumen y se otorga un nombre, un tamaño de segmento (únicamente grupos de volúmenes), una propiedad de controladora y una asignación de volumen a host al volumen. Los datos de volumen se cargan de manera equilibrada y automática en las controladoras, según sea necesario.



== Capacidad para volúmenes

Las unidades de la cabina de almacenamiento proporcionan capacidad de almacenamiento físico para los datos. Antes de comenzar a almacenar datos, es necesario configurar la capacidad asignada a los componentes lógicos conocidos como pools o grupos de volúmenes. Estos objetos de almacenamiento se utilizan para configurar, almacenar, mantener y conservar los datos en la cabina de almacenamiento.



=== Capacidad para crear y expandir volúmenes

Es posible crear volúmenes a partir de la capacidad sin asignar o de la capacidad libre en un pool o grupo de volúmenes.

* Cuando se crea un volumen a partir de capacidad sin asignar, es posible crear un pool o grupo de volúmenes y el volumen al mismo tiempo.
* Cuando se crea un volumen a partir de capacidad libre, se crea un volumen adicional en un pool o grupo de volúmenes existente.después de expandir la capacidad del volumen, debe aumentar manualmente el tamaño del sistema de archivos para que coincidan. La forma de hacerlo depende del sistema de archivos utilizado. Para obtener detalles, compruebe la documentación del sistema operativo del host.



NOTE: La interfaz del complemento no proporciona ninguna opción para crear volúmenes finos.



=== Capacidad notificada para volúmenes

La capacidad notificada del volumen es igual a la cantidad de capacidad de almacenamiento físico asignada. Se debe presentar la cantidad de capacidad de almacenamiento físico completa. El espacio asignado físicamente es igual al espacio que se notifica al host.

Normalmente, la capacidad notificada de un volumen se establece como la capacidad máxima hasta la que se cree que el volumen se extenderá. Los volúmenes ofrecen un rendimiento alto y previsible para las aplicaciones. Esto se debe principalmente a que toda la capacidad del usuario se reserva y se asigna en la creación.



=== Límites de capacidad

La capacidad mínima de un volumen es 1 MIB y la capacidad máxima se determina en función de la cantidad de unidades en el pool o el grupo de volúmenes y su capacidad.

Al aumentar la capacidad notificada para un volumen, tenga en cuenta las siguientes directrices:

* Puede especificar hasta tres espacios decimales (por ejemplo, 65 65.375 GIB).
* La capacidad debe ser menor (o igual) que el máximo disponible en el grupo de volúmenes. Al crear un volumen, se asigna previamente algo de capacidad adicional para la migración del tamaño de segmentos dinámico (DSS). La migración DSS es una función del software que permite cambiar el tamaño de los segmentos de un volumen.
* Algunos sistemas operativos host admiten volúmenes de más de 2 TIB (el sistema operativo host determina la capacidad notificada máxima). De hecho, algunos sistemas operativos host admiten volúmenes de hasta 128 TIB. Consulte la documentación del sistema operativo host para obtener más detalles.




== Cargas de trabajo específicas de una aplicación

Al crear un volumen, se debe seleccionar una carga de trabajo para personalizar la configuración de la cabina de almacenamiento para una aplicación específica.

Una carga de trabajo es un objeto de almacenamiento que admite una aplicación. Se pueden definir una o más cargas de trabajo o instancias por aplicación. En algunas aplicaciones, el sistema configura la carga de trabajo para contener volúmenes con características subyacentes similares. Estas características de volumen se optimizan según el tipo de aplicación que es compatible con la carga de trabajo. Por ejemplo, si crea una carga de trabajo que es compatible con la aplicación Microsoft SQL Server y, a continuación, crea volúmenes para esa carga de trabajo, las características de volumen subyacentes se optimizan para ser compatibles con Microsoft SQL Server.

Durante la creación del volumen, el sistema solicita que se respondan preguntas acerca del uso de la carga de trabajo. Por ejemplo, si se crean volúmenes para Microsoft Exchange, se consultará cuántos buzones se necesitan, cuáles son los requisitos de capacidad promedio del buzón y cuántas copias de la base de datos se desean. El sistema utiliza esta información para crear una configuración de volumen óptima para el usuario, que se puede editar en caso de ser necesario. De manera opcional, es posible omitir este paso en la secuencia de creación de volúmenes.



=== Tipos de cargas de trabajo

Es posible crear dos tipos de cargas de trabajo: Específicas para una aplicación y de otro tipo.

* *Específico de la aplicación* -- cuando se crean volúmenes con una carga de trabajo específica de la aplicación, el sistema puede recomendar una configuración de volumen optimizada para minimizar la contención entre las E/S de la carga de trabajo de la aplicación y otro tráfico de la instancia de la aplicación. Las características del volumen, como tipo de I/o, tamaño de segmentos, propiedad de la controladora, y caché de lectura y escritura, se recomiendan y se optimizan automáticamente para las cargas de trabajo que se crean para los siguientes tipos de aplicaciones.
+
** Microsoft SQL Server
** Servidor de Microsoft Exchange
** Aplicaciones de videovigilancia
** VMware ESXi (para volúmenes que se usarán con Virtual Machine File System)
+
Se puede revisar la configuración de volumen recomendada y editar, añadir o eliminar volúmenes y características recomendados por el sistema mediante el cuadro de diálogo Añadir/editar volúmenes.



* *Otros (o aplicaciones sin compatibilidad con la creación de volúmenes específicos)* -- Otras cargas de trabajo utilizan una configuración de volumen que debe especificar manualmente cuando desea crear una carga de trabajo no asociada con una aplicación específica, o si el sistema no posee la optimización integrada para la aplicación que piensa utilizar en la cabina de almacenamiento. Debe especificar manualmente la configuración del volumen en el cuadro de diálogo Añadir/editar volúmenes.




=== Vistas de aplicaciones y cargas de trabajo

Para ver aplicaciones y cargas de trabajo, inicie System Manager. Desde esa interfaz, es posible ver la información asociada a una carga de trabajo específica de la aplicación de dos maneras diferentes:

* Es posible seleccionar la pestaña aplicaciones y cargas de trabajo en el icono volúmenes para ver los volúmenes de la cabina de almacenamiento agrupados por carga de trabajo, además del tipo de aplicación con la que está asociada la carga de trabajo.
* Es posible seleccionar la pestaña aplicaciones y cargas de trabajo en el icono rendimiento para ver métricas de rendimiento (latencia, IOPS y MB) de objetos lógicos. Los objetos se agrupan por aplicación y carga de trabajo asociada. Al recoger estos datos de rendimiento en intervalos regulares, se pueden establecer mediciones de referencia y analizar tendencias, que pueden ayudar a investigar problemas relacionados con el rendimiento de I/O.

