---
permalink: install-hw-cabling/power-cable-task.html 
sidebar: sidebar 
keywords: cabling, cables, power cable, power cabling, power supply cabling, E-Series, eseries, E2800, E5700, EF300, EF600, DE212C, DE224C, DE460C 
summary: Conecte las fuentes de alimentación de cada componente a circuitos de alimentación separados. 
---
= Cableado de alimentación del sistema de almacenamiento (E-Series)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conectar las fuentes de alimentación de cada componente a circuitos de alimentación separados.

.Antes de empezar
* Ha confirmado que su ubicación proporciona la potencia necesaria.
* Los dos interruptores de alimentación de las dos fuentes de alimentación de la bandeja deben estar apagados.


.Acerca de esta tarea
La fuente de alimentación del sistema de almacenamiento debe poder adaptarse a los requisitos de alimentación de la nueva bandeja de unidades. Para obtener más información acerca del consumo de alimentación del sistema de almacenamiento, consulte https://hwu.netapp.com/Controller/Index?platformTypeId=2357027["Hardware Universe"^].

.Paso
. Conecte un cable de alimentación a cada una de las unidades de fuentes de alimentación del sistema de almacenamiento.
. Conecte los dos cables de alimentación de cada bandeja a diferentes unidades de distribución de alimentación (PDU) en el armario o rack.
. Encienda ambos interruptores de alimentación.
+

NOTE: Los sistemas de almacenamiento EF300 y EF600 no tienen switches de alimentación. Se encenderán tan pronto como se conecten los cables.


