---
permalink: maintenance-e5700/index.html 
sidebar: sidebar 
keywords: E5700 maintenance, repair E5700, replace E5700 components, E5724, EF570, E5760 
summary: Mantenga el hardware de E5700 
---
= Mantenga el hardware de E5700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba realizar procedimientos de mantenimiento en el hardware. En esta sección se incluyen los procedimientos específicos para el mantenimiento de los componentes del sistema E5700.

En los procedimientos de esta sección se asume que el sistema E5700 ya se ha puesto en marcha en el entorno E-Series.



== Componentes del sistema

Para el sistema de almacenamiento E5700, puede realizar procedimientos de mantenimiento en los siguientes componentes.

[cols="25,65"]
|===


 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/batteries-intro-concept.html["Pilas"]
 a| 
Se incluye una batería con un contenedor de controladora y mantiene los datos almacenados en caché si falla la alimentación de CA.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/controllers-overview-concept.html["Controladoras"]
 a| 
Una controladora consta de una placa, un firmware y un software. Controla las unidades e implementa las funciones de System Manager.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/canisters-overview-supertask-concept.html["Contenedores"]
 a| 
Los contenedores constan de tres tipos distintos: Contenedores de alimentación/ventilador (fuentes de alimentación) que proporcionan una fuente de alimentación redundante y una refrigeración adecuada en una bandeja de controladoras o de 24 unidades de 12 o de unidades; contenedores de alimentación que se usan para la redundancia de alimentación en una bandeja de controladoras o bandeja de unidades de 60 unidades; y los contenedores de ventiladores que se usan para refrigerar la bandeja de controladoras de 60 unidades o la bandeja de unidades.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/drives-overview-supertask-concept.html["Unidades"]
 a| 
Una unidad es un dispositivo mecánico electromagnético que proporciona medios de almacenamiento físico para datos.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/hics-overview-supertask-concept.html["Tarjetas de interfaz del host (HIC)"]
 a| 
En forma opcional, se puede instalar una tarjeta de interfaz del host (HIC) en un contenedor de controladora. La controladora E5700 incluye puertos de host incorporados en la tarjeta de la controladora misma, como también puertos de host en una HIC opcional. Los puertos de host que están incorporados en la controladora se denominan puertos de host de la placa base. Los puertos de host que están incorporados en HIC se denominan puertos de HIC.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/hpp-overview-supertask-concept.html["Protocolo de puerto de host"]
 a| 
Es posible convertir el protocolo de un host a otro protocolo para poder establecer la compatibilidad y la comunicación.

|===