---
permalink: maintenance-ef50-ef80/io-module-overview.html 
sidebar: sidebar 
keywords: ef50, ef80, replace io module, upgrade io module, io module overview 
summary: Los sistemas de almacenamiento EF50 y EF80 ofrecen flexibilidad a la hora de sustituir o actualizar los módulos de E/S para mejorar la conectividad de red y el rendimiento, y aumentar la capacidad de almacenamiento. 
---
= Infórmate sobre el mantenimiento de los módulos de E/S de los sistemas de almacenamiento EF50 y EF80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas de almacenamiento EF50 y EF80 ofrecen flexibilidad a la hora de sustituir o actualizar los módulos de E/S para mejorar la conectividad de red y el rendimiento, y aumentar la capacidad de almacenamiento.

* link:io-module-replace.html["Reemplazar un módulo de E/S"]
+
Cuando un módulo de E/S de tu sistema de almacenamiento falla, puedes reemplazarlo por el mismo tipo de módulo de E/S para devolver el sistema de almacenamiento a su estado óptimo de funcionamiento.

* link:io-module-upgrade.html["Actualizar un módulo de E/S"]
+
Puedes actualizar los módulos de E/S de tu sistema de almacenamiento para aumentar el número de puertos de host y mejorar la conectividad de red, ampliar la capacidad de tu sistema para manejar el tráfico de datos y conectar bandejas de expansión SAS.

+

NOTE: Los módulos de E/S de expansión SAS son compatibles con los sistemas de almacenamiento que ejecutan SANtricity 12.10 o una versión posterior.


