---
permalink: maintenance-ef600/index.html 
sidebar: sidebar 
keywords: EF300 maintenance, EF600 maintenance, repairing EF300, repairing EF600, EF600C, EF300C replace EF300 components, replace EF600 components 
summary: Mantener el hardware de EF300 y EF600 
---
= Mantenimiento de hardware EF300 y EF600
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba realizar procedimientos de mantenimiento en el hardware. En esta sección se incluyen los procedimientos específicos para el mantenimiento de los componentes del sistema EF300, EF600, EF300C o EF600C.

En los procedimientos de esta sección se asume que el sistema EF300 o EF600 ya se ha puesto en marcha en el entorno E-Series.



== Componentes del sistema

Para los sistemas de almacenamiento EF300, EF600, EF300C y EF600C, se pueden realizar procedimientos de mantenimiento en los siguientes componentes.

[cols="25,65"]
|===


 a| 
https://docs.netapp.com/us-en/e-series/maintenance-ef600/batteries-overview-requirements-concept.html["Pilas"]
 a| 
Se incluye una batería con una controladora y conserva los datos almacenados en caché si falla la alimentación de CA.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-ef600/controllers-overview-supertask-concept.html["Controladoras"]
 a| 
Una controladora consta de una placa, un firmware y un software. Controla las unidades e implementa las funciones de System Manager de SANtricity.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-ef600/dimms-overview-supertask-concept.html["DIMM"]
 a| 
Debe sustituir un DIMM (módulo de memoria en línea dual) cuando haya una falta de coincidencia en la memoria o tenga un DIMM fallido.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-ef600/drives-overview-supertask-concept.html["Unidades"]
 a| 
Una unidad es un dispositivo que proporciona medios de almacenamiento físico para datos.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-ef600/fans-overview-requirements-replacing2-concept.html["Ventiladores"]
 a| 
Cada bandeja de controladoras o bandeja de unidades EF300 o EF600 incluye cinco ventiladores para refrigerar la controladora.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-ef600/hics-overview-supertask-concept.html["Tarjetas de interfaz del host (HIC)"]
 a| 
Se debe instalar una tarjeta de interfaz del host (HIC) en un contenedor de controladora. La controladora EF600 incluye puertos de host en la HIC opcional. Los puertos de host que están incorporados en HIC se denominan puertos de HIC.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-ef600/hpp-overview-supertask-concept.html["Protocolo de puerto de host"]
 a| 
Es posible convertir el protocolo de un host a otro protocolo para poder establecer la compatibilidad y la comunicación.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-ef600/power-overview-requirements2-concept.html["Fuentes de alimentación"]
 a| 
Un suministro de alimentación proporciona una fuente de alimentación redundante en una bandeja de controladoras.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-ef600/sas-overview-supertask-concept.html["Tarjetas de expansión SAS"]
 a| 
Es posible instalar una tarjeta de ampliación SAS en un contenedor de controladora. El controlador EF300 admite la ampliación SAS.

|===