---
permalink: config-windows/index.html 
sidebar: sidebar 
keywords: express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Utilice la configuración exprés para un host Windows con un sistema E-Series. 
---
= Información general sobre la configuración exprés de Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El método exprés de Windows para instalar la cabina de almacenamiento y acceder a System Manager de SANtricity es adecuado para configurar un host de Windows independiente en un sistema E-Series. Está diseñado para poner en funcionamiento el sistema de almacenamiento con la mayor rapidez posible y sin apenas tomar decisiones.



== Descripción general del procedimiento

El método Express incluye los siguientes pasos, que también se describen en el link:understand-windows-concept.html["Flujo de trabajo de Windows"].

. Configure uno de los siguientes entornos de comunicación:
+
** link:fc-perform-specific-task.html["Fibre Channel (FC)"]
** link:iscsi-perform-specific-task.html["ISCSI"]
** link:sas-perform-specific-task.html["SAS"]


. Crear volúmenes lógicos en la cabina de almacenamiento.
. Hacer que los volúmenes estén disponibles para el host de datos.




== Obtenga más información

* Ayuda en línea: Describe cómo usar System Manager de SANtricity para completar tareas de configuración y gestión del almacenamiento. Está disponible en el producto.
* https://kb.netapp.com/["Base de conocimientos de NetApp"^] (Una base de datos de artículos) -- ofrece información sobre solución de problemas, preguntas más frecuentes e instrucciones para una amplia gama de productos y tecnologías de NetApp.
* http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] -- le permite buscar configuraciones de productos y componentes de NetApp que cumplan con los estándares y requisitos especificados por NetApp.
* http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343["Documentación de NetApp: Utilidades de host"^] -- proporciona documentación para la versión actual de Windows Unified Host Utilities.

