---
permalink: config-windows/install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Windows Unified Host Utilities, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries, SMcli, SMdevices 
summary: Instale el método exprés de Windows Unified Host Utilities para Windows. 
---
= Instale y configure Linux Unified Host Utilities en E-Series - Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las herramientas de Windows Unified Host Utilities le ayudan a conectar equipos host con sistemas de almacenamiento de NetApp y establecer los parámetros necesarios en equipos host. También es posible configurar tiempos de espera en el disco adecuados para obtener el mejor rendimiento de lectura/escritura con el sistema de almacenamiento de NetApp.


NOTE: Para obtener más información, consulte la _Windows Host Utilities Installation Guide,_ que se encuentra en http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343["Documentación de NetApp: Utilidades de host"^].

.Pasos
. Utilice la http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] Para determinar la versión adecuada de Unified Host Utilities que se debe instalar.
+
Las versiones se enumeran en una columna dentro de cada configuración compatible.

. Descargue las utilidades unificadas de host desde http://mysupport.netapp.com["Soporte de NetApp"^].
+

NOTE: Este paquete de utilidades no se puede instalar mediante el instalador de SANtricity Storage Manager.

+

NOTE: Como alternativa, es posible usar el comando SMcli `-identifyDevices` Para realizar las mismas funciones que la herramienta Unified Host Utility. La interfaz SMcli se incluye en el sistema operativo SANtricity y se puede descargar a través de SANtricity System Manager. Para obtener más información sobre cómo descargar la interfaz SMcli mediante SANtricity System Manager, consulte la https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["Descargue el tema de la CLI en la ayuda en línea de comandos de SANtricity System Manager"^].


