---
permalink: config-windows/install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Windows Unified Host Utilities, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Instale el método exprés de Windows Unified Host Utilities para Windows. 
---
= Instale y configure Windows Unified Host Utilities
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las herramientas de Windows Unified Host Utilities le ayudan a conectar equipos host con sistemas de almacenamiento de NetApp y establecer los parámetros necesarios en equipos host. También es posible configurar tiempos de espera en el disco adecuados para obtener el mejor rendimiento de lectura/escritura con el sistema de almacenamiento de NetApp.


NOTE: Para obtener más información, consulte la _Windows Host Utilities Installation Guide,_ que se encuentra en http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343["Documentación de NetApp: Utilidades de host"^].

.Pasos
. Utilice la http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^] Para determinar la versión adecuada de Unified Host Utilities que se debe instalar.
+
Las versiones se enumeran en una columna dentro de cada configuración compatible.

. Descargue las utilidades unificadas de host desde http://mysupport.netapp.com["Soporte de NetApp"^].
+

NOTE: Este paquete de utilidades no se puede instalar mediante el instalador de SANtricity Storage Manager.

+

NOTE: También puede utilizar la utilidad SMdevices de SANtricity para realizar las mismas funciones que la herramienta Unified Host Utility. La utilidad SMdevices se incluye como parte del paquete SMutils. El paquete SMutils es una recogida de utilidades para verificar lo que el host puede ver en la cabina de almacenamiento. Se incluye como parte de la instalación del software SANtricity.


