---
permalink: upgrade-controllers/upgrade-unlock-drives-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, unlock drives, key management, Drive Security, 
summary: Si va a actualizar las controladoras E2800 y E5700 y la función Drive Security está habilitada, debe desbloquear manualmente las unidades. 
---
= Desbloquee las unidades E-Series
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La función Drive Security de estas controladoras bloqueará las unidades de forma parcial, externa o interna. Si la función Drive Security está habilitada, es necesario desbloquear manualmente estas unidades.

Siga el procedimiento adecuado para:

* <<Gestión de claves internas>>
* <<Gestión de claves externas>>




== Gestión de claves internas

Siga estos pasos para la gestión de claves internas cuando se bloqueen todas las unidades.

.Acerca de esta tarea
Los controladores recientemente intercambiados se bloquearán con un código de visualización de siete segmentos de *L5*. Este bloqueo se produce cuando ninguna unidad puede realizar una sincronización de autocodificación (ACS). Una vez importada la clave de seguridad, ACS reanudará y actualizará las nuevas controladoras.


NOTE: Si no utiliza el puerto de administración 1, intente con otras direcciones IP predeterminadas: + Ctrl un puerto 1: 169.254.128.101 + Ctrl un puerto 2: 169.254.128.102 + Ctrl B puerto 1: 169.254.128.101 + Ctrl B puerto 2: 169.254.128.102

.Pasos
. Establezca una conexión ethernet directa y privada entre la cabina de almacenamiento y el ordenador portátil o PC del cliente SANtricity. Para hacer esto:
+
.. Utilice un cable ethernet RJ45 para conectar el portátil al puerto de gestión 1 de la controladora A.
.. Para completar la conexión, es posible que deba asignar el portátil a una dirección IP en la misma subred que la controladora A. Durante el bloqueo de la controladora, la controladora A se establece de forma predeterminada en la dirección de administración de 169.254.128.101. Así que puede asignar el portátil a una subred como "169.254.128.201".


. Usando la dirección IP 169.254.128.101 con el nombre de usuario *admin* y la contraseña en blanco, importe la clave interna usando el `import storageArray securityKey file` comando CLI, con la clave de seguridad guardada desde link:prepare-upgrade-controllers-task.html["Prepare la actualización de las controladoras"]. Para obtener información sobre el uso de este comando, consulte la https://docs.netapp.com/us-en/e-series-cli/index.html["Referencia de la interfaz de línea de comandos"].
+
*Ejemplo:* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
Como alternativa, puede importar la clave interna a través de la API REST a través de la siguiente llamada: `/storage-systems/{system-id}/security-key/import`



Las controladoras continuarán con el proceso de sincronización de autocodificación desde las unidades y reiniciarán. Tras reiniciar, se podrá acceder a las controladoras mediante la configuración IP original.



== Gestión de claves externas

Siga estos pasos para la gestión de claves externas cuando se bloquean todas las unidades.

.Acerca de esta tarea
Los controladores recientemente intercambiados se bloquearán con un código de visualización de siete segmentos de *L5*. Este bloqueo se produce cuando ninguna unidad puede realizar una sincronización de autocodificación (ACS). Una vez importada la clave de seguridad, ACS reanudará y actualizará las nuevas controladoras.

.Pasos
. Establezca una conexión ethernet directa y privada entre la cabina de almacenamiento y el ordenador portátil o PC del cliente SANtricity. Para hacer esto:
+
.. Utilice un cable ethernet RJ45 para conectar el portátil al puerto de gestión 1 de la controladora A.
.. Para completar la conexión, es posible que deba asignar el portátil a una dirección IP en la misma subred que la controladora A. Durante el bloqueo de la controladora, la controladora A se establece de forma predeterminada en la dirección de administración de 169.254.128.101. Así que puede asignar el portátil a una subred como "169.254.128.201".


. Con la clave de seguridad guardada desde link:prepare-upgrade-controllers-task.html["Prepare la actualización de las controladoras"], importe la clave externa a la dirección IP 169.254.128.101 con el nombre de usuario *admin* y la contraseña en blanco.
+
*Ejemplo:* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
Como alternativa, puede importar la clave externa a través de la API de REST a través de la siguiente llamada: `/storage-systems/{system-id}/security-key/import`

+
Las controladoras continuarán con el proceso de sincronización de autocodificación desde las unidades y reiniciarán. Tras reiniciar, se podrá acceder a las controladoras mediante la configuración IP original.

. (Opcional) Si es necesario, las unidades se pueden cambiar siguiendo lo siguiente:
+
*Ejemplo:* `SMcli <original_controller _ip> -u admin -p "<original_array_password>" -c "create storageArray securityKey" passPhrase=\"passPhraseString\" file=\"filename\";”`


